### ISSUE TITLE
1. Homepage template 

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#136]

**Comment by murphybarb** [comment]
**1. Homepage template**

**Attached files:** 
- design mockup of the homepage template, .jpg format (desktop, mobile and hover states)
- ‘marked up’ copy of above template – indicates specific design details (to be added)   
- "Header Footer links BCcampus.ca.pdf" – indicates the location of links in template header and footer

Reference information in the [NextCloud project folder](https://cloud.bccampus.ca/index.php/apps/files/?dir=/*Current%20Jobs/283%20Web%20Consolidation%20Project/Visual%20Design/BCcampus.ca/BCcampus.ca%20%E2%80%93%C2%A0Assests%20for%20DevOps&fileid=2956794)
- List of all templates and menu treatment - file name "templates_sitemap BCcampus.ca.pdf"
- PDF containing 'markup' copies of **all templates** and menu treatments – file name "BCcampus.ca template markup.pdf"
- PDF containing style information for the **entire site** - file name "BCcampus.ca-website-style-guide.pdf"
- Image assets folder containing **all required images** for development – Folder file name "image assets"
 
![1 home-desktop-](https://user-images.githubusercontent.com/11672469/43984663-ce43da44-9cb6-11e8-8589-5a4ee3474ee8.jpg)
![1 home-desktop-hover](https://user-images.githubusercontent.com/11672469/43984664-ce9cf4bc-9cb6-11e8-990e-d7c6511e1304.jpg)
![1 home-mobile](https://user-images.githubusercontent.com/11672469/43984670-d4577922-9cb6-11e8-8f7b-c07e53982227.jpg)



Note: The NextCloud folder has been shared with both Brad and Alex.

**Comment by bdolor** [comment]
Home template is complete via https://github.com/BCcampus/bcc-sage/pull/169 with placeholders for  individual components.
https://helga.bccampus.ca/wp/bcc/
