### ISSUE TITLE
2. Abouts Us Landing Page

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#137]

**Comment by murphybarb** [comment]
**2. About Us Landing Page**

**Attached files:** 
- design mockup of the homepage template, .jpg format (desktop and mobile)
- ‘marked up’ copy of above template – indicates specific design details (to be added)   
- "Header Footer links BCcampus.ca.pdf" – indicates the location of links in template header and footer

Reference information in the [NextCloud project folder](https://cloud.bccampus.ca/index.php/apps/files/?dir=/*Current%20Jobs/283%20Web%20Consolidation%20Project/Visual%20Design/BCcampus.ca/BCcampus.ca%20%E2%80%93%C2%A0Assests%20for%20DevOps&fileid=2956794)
- List of all templates and menu treatment - file name "templates_sitemap BCcampus.ca.pdf"
- PDF containing 'markup' copies of **all templates** and menu treatments – file name "BCcampus.ca template markup.pdf"
- PDF containing style information for the **entire site** - file name "BCcampus.ca-website-style-guide.pdf"
- Image assets folder containing **all required images** for development – Folder file name "image assets"
![2 about us-desktop](https://user-images.githubusercontent.com/11672469/43984736-48880082-9cb7-11e8-8589-30eef6a52390.jpg)
![2 about us-mobile](https://user-images.githubusercontent.com/11672469/43984737-4aacdf0e-9cb7-11e8-8040-a70e0de321d2.jpg)

**Comment by bdolor** [comment]
About us template is complete via https://github.com/BCcampus/bcc-sage/pull/169 with placeholders for individual components. https://helga.bccampus.ca/wp/bcc/about-us/

Administrators are able to select the about us template. 
![image](https://user-images.githubusercontent.com/2048170/44165004-74c11580-a07c-11e8-8ba2-17928f2ba483.png)
