### ISSUE TITLE
3. Projects Landing Page

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#138]

**Comment by murphybarb** [comment]
**3. Projects Landing Page**

**Attached files:** 
- design mockup of the homepage template, .jpg format (desktop and mobile)
- ‘marked up’ copy of above template – indicates specific design details (to be added)   
- "Header Footer links BCcampus.ca.pdf" – indicates the location of links in template header and footer

Reference information in the [NextCloud project folder](https://cloud.bccampus.ca/index.php/apps/files/?dir=/*Current%20Jobs/283%20Web%20Consolidation%20Project/Visual%20Design/BCcampus.ca/BCcampus.ca%20%E2%80%93%C2%A0Assests%20for%20DevOps&fileid=2956794)
- List of all templates and menu treatment - file name "templates_sitemap BCcampus.ca.pdf"
- PDF containing 'markup' copies of **all templates** and menu treatments – file name "BCcampus.ca template markup.pdf"
- PDF containing style information for the **entire site** - file name "BCcampus.ca-website-style-guide.pdf"
- Image assets folder containing **all required images** for development – Folder file name "image assets"

![3 projects landing-desktop](https://user-images.githubusercontent.com/11672469/43984764-7317e1aa-9cb7-11e8-8d85-6a0b49c4b360.jpg)
![3 projects landing-mobile](https://user-images.githubusercontent.com/11672469/43984765-76d5e1b6-9cb7-11e8-9118-a317f17e00fb.jpg)

**Comment by bdolor** [comment]
projects landing page is complete via https://github.com/BCcampus/bcc-sage/pull/169 with placeholders for individual components. https://helga.bccampus.ca/wp/bcc/projects/

Administrators are able to select the template from the dashboard. 
![image](https://user-images.githubusercontent.com/2048170/44164841-fc5a5480-a07b-11e8-9456-4339dce39060.png)
