### ISSUE TITLE
4. Grants and calls for propsoals landing page

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#139]

**Comment by murphybarb** [comment]
**4. Grants and calls for proposals landing page**

**Attached files:** 
- design mockup of the **Grants and calls for proposals landing page template**, .jpg format (desktop and mobile)
- ‘marked up’ copy of above template – indicates specific design details (to be added)   
- "Header Footer links BCcampus.ca.pdf" – indicates the location of links in template header and footer

Reference information in the [NextCloud project folder](https://cloud.bccampus.ca/index.php/apps/files/?dir=/*Current%20Jobs/283%20Web%20Consolidation%20Project/Visual%20Design/BCcampus.ca/BCcampus.ca%20%E2%80%93%C2%A0Assests%20for%20DevOps&fileid=2956794)
- List of all templates and menu treatment - file name "templates_sitemap BCcampus.ca.pdf"
- PDF containing 'markup' copies of **all templates** and menu treatments – file name "BCcampus.ca template markup.pdf"
- PDF containing style information for the **entire site** - file name "BCcampus.ca-website-style-guide.pdf"
- Image assets folder containing **all required images** for development – Folder file name "image assets"

![4 grants and calls for proposals landing-desktop](https://user-images.githubusercontent.com/11672469/43984844-14a0b808-9cb8-11e8-9432-28477db82b8a.jpg)
![4 grants and calls for proposals landing-mobile](https://user-images.githubusercontent.com/11672469/43984846-182993d2-9cb8-11e8-92a1-f4f04f4b9dd2.jpg)

**Comment by bdolor** [comment]
Grants and Calls for Proposal landing page template complete via https://github.com/BCcampus/bcc-sage/pull/169 with placeholders in place for individual components. https://helga.bccampus.ca/wp/bcc/grants-calls-for-proposal/

Admins can select the template from the dashboard: 
![image](https://user-images.githubusercontent.com/2048170/44165596-0715e900-a07e-11e8-9a01-04180c324eaf.png)
