### ISSUE TITLE
5. Topics of practice landing page

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#140]

**Comment by murphybarb** [comment]
**5. Topics of practice landing page**

**Attached files:** 
- design mockup of the **5. Topics of practice landing page**, .jpg format (desktop and mobile)
- ‘marked up’ copy of above template – indicates specific design details (to be added)   
- "Header Footer links BCcampus.ca.pdf" – indicates the location of links in template header and footer

Reference information in the [NextCloud project folder](https://cloud.bccampus.ca/index.php/apps/files/?dir=/*Current%20Jobs/283%20Web%20Consolidation%20Project/Visual%20Design/BCcampus.ca/BCcampus.ca%20%E2%80%93%C2%A0Assests%20for%20DevOps&fileid=2956794)
- List of all templates and menu treatment - file name "templates_sitemap BCcampus.ca.pdf"
- PDF containing 'markup' copies of **all templates** and menu treatments – file name "BCcampus.ca template markup.pdf"
- PDF containing style information for the **entire site** - file name "BCcampus.ca-website-style-guide.pdf"
- Image assets folder containing **all required images** for development – Folder file name "image assets"

![5 topics of practice landing-desktop](https://user-images.githubusercontent.com/11672469/43984973-c759a6d0-9cb8-11e8-8465-1f1b602424b8.jpg)
![5 topics of practice landing-mobile](https://user-images.githubusercontent.com/11672469/43984976-ca5de530-9cb8-11e8-92ab-773c4a1ec5bc.jpg)

**Comment by bdolor** [comment]
Topics of Practice template is complete via https://github.com/BCcampus/bcc-sage/pull/169 with placeholder for individual components. https://helga.bccampus.ca/wp/bcc/topics-of-practice/

Admins are able to select the template. 
![image](https://user-images.githubusercontent.com/2048170/44165131-c7023680-a07c-11e8-9b6d-92460088cbe2.png)
