### ISSUE TITLE
9. News landing page

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#144]

**Comment by murphybarb** [comment]
**9. News landing page**

**Attached files:** 
- design mockup of the **9. News landing page**, .jpg format (desktop and mobile)
- ‘marked up’ copy of above template – indicates specific design details (to be added)   
- "Header Footer links BCcampus.ca.pdf" – indicates the location of links in template header and footer

Reference information in the [NextCloud project folder](https://cloud.bccampus.ca/index.php/apps/files/?dir=/*Current%20Jobs/283%20Web%20Consolidation%20Project/Visual%20Design/BCcampus.ca/BCcampus.ca%20%E2%80%93%C2%A0Assests%20for%20DevOps&fileid=2956794)
- List of all templates and menu treatment - file name "templates_sitemap BCcampus.ca.pdf"
- PDF containing 'markup' copies of **all templates** and menu treatments – file name "BCcampus.ca template markup.pdf"
- PDF containing style information for the **entire site** - file name "BCcampus.ca-website-style-guide.pdf"
- Image assets folder containing **all required images** for development – Folder file name "image assets"


![9 news landing-desktop](https://user-images.githubusercontent.com/11672469/43985160-0c925782-9cba-11e8-9d7b-b2da11ef86e8.jpg)
![9 news landing-mobilel](https://user-images.githubusercontent.com/11672469/43985162-114a2962-9cba-11e8-8ceb-62d304e39052.jpg)

**Comment by bdolor** [comment]
News Template is complete via https://github.com/BCcampus/bcc-sage/pull/170 with placeholders for individual components. https://helga.bccampus.ca/wp/bcc/news-4/

Admins can select News Template from within the dashboard.
![image](https://user-images.githubusercontent.com/2048170/44171405-fc178480-a08e-11e8-9137-8bb03e086c0b.png)
