### ISSUE TITLE
10. News category page

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#145]

**Comment by murphybarb** [comment]
**10. News category page**

**Attached files:** 
- design mockup of the **10. News category page**, .jpg format (desktop and mobile)
- ‘marked up’ copy of above template – indicates specific design details (to be added)   
- "Header Footer links BCcampus.ca.pdf" – indicates the location of links in template header and footer

Reference information in the [NextCloud project folder](https://cloud.bccampus.ca/index.php/apps/files/?dir=/*Current%20Jobs/283%20Web%20Consolidation%20Project/Visual%20Design/BCcampus.ca/BCcampus.ca%20%E2%80%93%C2%A0Assests%20for%20DevOps&fileid=2956794)
- List of all templates and menu treatment - file name "templates_sitemap BCcampus.ca.pdf"
- PDF containing 'markup' copies of **all templates** and menu treatments – file name "BCcampus.ca template markup.pdf"
- PDF containing style information for the **entire site** - file name "BCcampus.ca-website-style-guide.pdf"
- Image assets folder containing **all required images** for development – Folder file name "image assets"

![10 news category-desktop](https://user-images.githubusercontent.com/11672469/43985187-49fcc616-9cba-11e8-88d6-908849945fe9.jpg)
![10 news category-mobile](https://user-images.githubusercontent.com/11672469/43985189-4ccadeaa-9cba-11e8-9599-1a11899716a7.jpg)

**Comment by bdolor** [comment]
this has been addressed in https://github.com/BCcampus/bcc-sage/issues/163
