### ISSUE TITLE
12. Mega menu

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#147]

**Comment by murphybarb** [comment]
**12. Mega menu**

**Attached files:** 
- design mockup of the **12. Mega menu**, .jpg format (desktop and mobile, showing 3 different states)
- ‘marked up’ copy of above template – indicates specific design details (to be added)   

Reference information in the [NextCloud project folder](https://cloud.bccampus.ca/index.php/apps/files/?dir=/*Current%20Jobs/283%20Web%20Consolidation%20Project/Visual%20Design/BCcampus.ca/BCcampus.ca%20%E2%80%93%C2%A0Assests%20for%20DevOps&fileid=2956794)
- List of all templates and menu treatment - file name "templates_sitemap BCcampus.ca.pdf"
- PDF containing 'markup' copies of **all templates** and menu treatments – file name "BCcampus.ca template markup.pdf"
- PDF containing style information for the **entire site** - file name "BCcampus.ca-website-style-guide.pdf"
- Image assets folder containing **all required images** for development – Folder file name "image assets
![12 megamenu-grants-desktop](https://user-images.githubusercontent.com/11672469/43985273-f0e8798e-9cba-11e8-9f2e-e82630a8d5f2.jpg)
![12 megamenu-projects](https://user-images.githubusercontent.com/11672469/43985274-f0fe286a-9cba-11e8-9802-57bd5a20511e.jpg)
![12 megamenu-topics](https://user-images.githubusercontent.com/11672469/43985275-f1162b22-9cba-11e8-9d26-07245f11a14f.jpg)
![12 megamenu-grants-mobile](https://user-images.githubusercontent.com/11672469/43985382-ee9fd162-9cbb-11e8-9698-26ca74b2f6f7.jpg)

**Comment by alex-418** [comment]
Things left to do: 
1. Check that the `BCcampus/MegaWalker` class exists before adding the fields to the menu manager (this causes the site not to load if the composer dependency hasn't been added yet) 
2. Check that the `BCcampus/MegaWalkerEditor` class exists before returning the new walker (this causes to return an empty menu)
3. Styling - Padding as per the design
4. Decision about wether to use a feature imaged only in the megamenu (with the heading in the image), or if the heading should be text/css.

**Comment by alex-418** [comment]
@murphybarb Before I send over to validate, just wanted to double check the styling. I couldn't find anything in the folder about Megamenu styling (did I miss it?) The padding/line-height, and correct font-size is what i'm looking for. Here's what it looks like right now. If you're happy with that let me know, or let me know what changes are needed to the styling. Thank you 

![mega-menu styling](https://user-images.githubusercontent.com/17072191/45116877-f4388680-b108-11e8-8fa5-92146f81a356.png)

**Comment by murphybarb** [comment]
FYI: What you need is on way.

**Comment by alex-418** [comment]
@murphybarb Thanks. I've also updated the menu so it's floated right as per design: 

![menu_right](https://user-images.githubusercontent.com/17072191/45118362-25b35100-b10d-11e8-8078-d331ae83e315.png)

**Comment by murphybarb** [comment]
Ok, sorry for the delay. Was conferring with Jessica, the designer. There was nothing specific in the style guide regarding the mega menu. 

The one thing that needs adjusting is to add space above the bold section titles that would appear mid-list, to provide separation from each section. So for the above example it would be to add space above "Indigenization", "Learning and Teaching". 

I've attached an example: 
![ae3564a0-b158-11e8-a8d3-ceb81990af95](https://user-images.githubusercontent.com/11672469/45126102-72efec80-b126-11e8-966f-ea938b4cd251.png)

**Comment by alex-418** [comment]
@murphybarb I'm ready to walk you through how to create this mega menu on cert.
