### ISSUE TITLE
13. Mobile secondary menu

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#148]

**Comment by murphybarb** [comment]
**13. Mobile secondary menu**

**Attached files:** 
- design mockup of the **13. Mobile secondary menu**, .jpg format (mobile), inactive and active states

Reference information in the [NextCloud project folder](https://cloud.bccampus.ca/index.php/apps/files/?dir=/*Current%20Jobs/283%20Web%20Consolidation%20Project/Visual%20Design/BCcampus.ca/BCcampus.ca%20%E2%80%93%C2%A0Assests%20for%20DevOps&fileid=2956794)
- List of all templates and menu treatment - file name "templates_sitemap BCcampus.ca.pdf"
- PDF containing 'markup' copies of **all templates** and menu treatments – file name "BCcampus.ca template markup.pdf"
- PDF containing style information for the **entire site** - file name "BCcampus.ca-website-style-guide.pdf"
- Image assets folder containing **all required images** for development – Folder file name "image assets


![13 mobile secondary menu-dropdown](https://user-images.githubusercontent.com/11672469/43985438-4f6dda3e-9cbc-11e8-9fb9-10f8d5dfe037.jpg)
![13 mobile secondary menu](https://user-images.githubusercontent.com/11672469/43985439-4f8fcb6c-9cbc-11e8-9b07-f02e1e98757b.jpg)

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/bcc-sage/pull/175 (when it's merged, not yet on cert) It might need a styling tweak)
![mobile](https://user-images.githubusercontent.com/17072191/45241714-511b7480-b2a2-11e8-88f0-e5a8e337cb0b.png)

**Comment by bdolor** [comment]
functionality complete via https://github.com/BCcampus/bcc-sage/pull/175

**Comment by murphybarb** [comment]
Moving to done. 

Attaching screen cap of view on my mobile for reference for design review. 

![mobile view](https://user-images.githubusercontent.com/11672469/45329969-e8d5c880-b517-11e8-8c9e-5e6ef107d978.jpg)

**Comment by alex-418** [comment]
@stargraphicdesign FYI mobile menus issue documented above

**Comment by stargraphicdesign** [comment]
Can you be more specific as to what you need from me.
