### ISSUE TITLE
slideshow component on the homepage

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#149]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

## Feature Request

**Please provide use cases for changing the current behavior:**

The slideshow should be full width, but a maximum width set to 1600px. Any oversized screens will see it centered on the page at that size. The photo background should display using the background-cover technique. The blue overlay should cover 50% of the width. Ideally I’d like the text to align to the content wrapper, so it appears lined up with the text further down on the page. Same notes apply to the interior page headers.

**Other relevant information:**

mobile breakpoints for when the slideshow stops being a slideshow and become either a solid colour or static image.

**Comment by bdolor** [comment]
In terms of workflow...the relationship between the image, the title and the read more is pulling from existing content, to a maximum of three. 
Taxonomy of 'slideshow' would be the distinguishing 
- it would be ideal to be able to pull from both pages and posts (somehow)  
- featured image
- read more

**Comment by alex-418** [comment]
@murphybarb Slider is up on the homepage: https://helga.bccampus.ca/wp/bcc/

It uses a plugin called "Smart Slider", you'll find it as a menu item in the dashboard. To make displaying this on the homepage painless, we've added an option to the customizer menu where you add the slider ID under the Homepage Settings. This means you can change and preview the slider by changing the slider ID value.

Plugin: 
The reason for going with this plugin over the others, was the flexibility in design, good user interface, takes care of mobile/responsive design, and good developer track record/support. But more importantly the ability to export/import the slides. This allows us to contain and export all settings/styling/content of the slideshow, and import it again when we want to move this to production.

One caveat: 
In the design, there is a back/forward arrow before and after the green navigation dots. This was not possible without spending a significant amount more time. However, in the settings there are options to position these arrows elsewhere, please see if any of those meet your requirements.

**Comment by murphybarb** [comment]
@alex-418 this looks great! 

Can you confirm the final height of the slider images will be adjusted when the styling guide is applied in #157? The height of the slider is greater than what is indicated in the design mockup. 

I can validate once you confirm. 

PS - this thing looks like the shit. Nice job!

**Comment by alex-418** [comment]
@murphybarb Thanks. I can confirm the styling for width of the website is set at 1280px, so the slider will never be wider than that. But the height depends on the slider settings. It's set at 500px right now, what would you like it to be? This can all be set in the smart slider menu's "size" settings tab. 

![slider_size_settings](https://user-images.githubusercontent.com/17072191/45121298-92324e00-b115-11e8-9f62-7dd35784ab8b.png)

**Comment by alex-418** [comment]
@murphybarb I've set the height to 465px on cert. I've just logged in now and everything looks good.... Can you please provide screen shot of what you mean by deactivated, and not visible on the homepage?

**Comment by murphybarb** [comment]
Hey @alex-418 it looks ok now! The entire slider did not appear last time I looked.

The height looks good. 

Is there any way to use Helvetica Neue instead of Arial as the font for the text in the slider. I don't see it as an option in the fonts. But thougt I'd ask. Thanks!

**Comment by alex-418** [comment]
@murphybarb Yes, under settings the font can be changed. I've attached a screenshot for you here:

![font settings](https://user-images.githubusercontent.com/17072191/45238079-70f86b80-b295-11e8-900b-6cfa91667e4d.png)

**Comment by murphybarb** [comment]
Hey @alex-418, I saw that when poking around in there. But "Helvetica Neue" is not an option in the list. Are we able to do anything to make Helvetica Neue so as the font in the slider?

**Comment by alex-418** [comment]
@murphybarb After looking into this, it be added manually... but it actually it's not on the list because "Helvetica Neue" isn't considered a 'web safe font'. It looks like it's actually a font found on Macs. Basically what that means, is that a license would need to be purchased so that we can consistently deliver the same font across devices/browsers. A good solution would be to ask the designer to deliver a web-safe font option that would work across all browsers/devices without needing to purchase and install.

**Comment by murphybarb** [comment]
Validating. The slide is great, thanks for the hard work on this one ya'll. 

Can address font thing later.

**Comment by alex-418** [comment]
@stargraphicdesigner Please see issue with font above.

**Comment by stargraphicdesign** [comment]
As specified in the docs. The fonts would be specified in this order so anyone with Helvetica Neue installed will see it, and others will see Helvetica, pretty sure both contain the same weights used.

font-family: ‘Helvetica Neue’, Helvetica, Arial, sans-serif;
