### ISSUE TITLE
menu component on homepage 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#150]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

## Feature Request

**Please provide use cases for changing the current behavior:**

Topics of practice and projects (and others?) is a navigation menu, should display an image, and a description and a list of child pages. Looking at widgets and customizer api for possible implementation. Goal is to let content specialists modify content. 

If it's determined that the chevrons indicate a menu expansion, an alternative icon appropriate for links should be considered.

**Comment by murphybarb** [comment]
Hey @bdolor: 

This is static content, it is not meant to be pulled from anywhere. I have provided the content below. 

The intention of this content is: 
This “Topics of Practice” and "Projects" container will  be static content. The image and the headline will  remain the same."

**Topics of Practice**
At BCcampus, we support the adaptation and evolution of teaching and learning practices in post-secondary institutions across British Columbia through collaboration, communication, and innovation.

**Projects**
We actively participate in opportunities to improve the student experience in B.C. by facilitating technology advancements; enabling research activities; creating collaborative spaces; and more.

Does that  help?

**Comment by bdolor** [comment]
immensely. tks.
