### ISSUE TITLE
Create site header

### ISSUE THREAD

**Issue by alex-418** [BCcampus/bcc-sage#152]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

## Feature Request

**Please provide use cases for changing the current behavior:**

The site header includes two menus that can be edited by the site admin (two menu locations in theme). It should reflect the mockup in https://github.com/BCcampus/bcc-sage/issues/136,

**Comment by bdolor** [comment]
addressed in https://github.com/BCcampus/bcc-sage/pull/171

**Comment by bdolor** [comment]
Header is (mostly) complete via https://github.com/BCcampus/bcc-sage/pull/171
Once mega menu https://github.com/BCcampus/bcc-sage/issues/147 issue is resolved, this can be validated.

**Comment by murphybarb** [comment]
1. Still working on validating mega menu. 

2. Have comments on the top, secondary navigation ("Find an Open Textbook" "open.bccampus.ca" "Help" "Contact Us" search entry field"). All my comments are design related, so may be addressed in the design review? If so, I can move to the "done". Please advise best way to proceed. 

**Comments:** 

- I have attached screen cap for reference 

- The top, secondary navigation is intended to display in a smaller font than the primary, top navigation below it. In the design mockups the top, main navigation font size is 18 pt and the secondary, top nav is 15pt. I'm providing those for context of size relationship, as I realize you do not use pts. Using inspect element I found that changing the top, secondary nav to 14px looked ok. 

- The font in the top, secondary nav is intended to be bold 

- You'll see in the attached screen capture that two of the links are blue and two are grey. The blue would be Blue - #00a5e1 and the grey Dark Grey - #808285

- For the search field can we add more space between "Contact us" and the entry field 

![screen shot 2018-09-07 at 9 18 35 am](https://user-images.githubusercontent.com/11672469/45230845-09cfbc80-b27f-11e8-9bfe-a8c6395a31bc.png)

**Comment by murphybarb** [comment]
Moving to Done. 

Will address styling later.
