### ISSUE TITLE
Events component feature events

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#155]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

## Feature Request

4 feature events, limit of 2 displayed at a time randomly selected, which two are displayed. The require an image, a date (of the event) and a title. The image used will be a featured image. Some discussion will have to occur around the approach to responsive design. 

not clear on how featured events are selected for display, though events are a custom post type with access to taxonomies.

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/bcc-sage/pull/179
