### ISSUE TITLE
Events component upcoming 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#156]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

## Feature Request

upcoming events component is on the homepage is limited to the latest 3 that are not included in a featured event category/taxonomy. They include a featured image, a title, and link to the event.

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/bcc-sage/pull/179
