### ISSUE TITLE
Related news component 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#158]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

## Feature Request

Related news component limits to 3 related news items that are scoped by tags. The tag values are the name of the page it's on. The only difference in terms of display is on an individual page, when the three boxes become equal in width. They include featured images, date, and title.

**Comment by bdolor** [comment]
functionality of related news component is complete via https://github.com/BCcampus/bcc-sage/commit/04901183f20b2bd04f0e6a64be1d4381046326c2

final styling will be covered by https://github.com/BCcampus/bcc-sage/issues/157

can be validated on https://helga.bccampus.ca/wp/bcc/topics-of-practice/
https://helga.bccampus.ca/wp/bcc/grants-calls-for-proposal/
https://helga.bccampus.ca/wp/bcc/about-us/
https://helga.bccampus.ca/wp/bcc/projects/

**Comment by murphybarb** [comment]
@bdolor Validating functionality. 

Have one question regarding the content. In the design layouts for the URLs listed above the "Related News" section contains a "feature" on the left hand side of the container. I've attached a screen cap for reference. Was that an oversight that it does not appear or will that be addressed when the style guide is applied? 

![screen shot 2018-09-07 at 10 08 56 am](https://user-images.githubusercontent.com/11672469/45232951-19063880-b286-11e8-8fdc-9fbed5507db7.png)

**Comment by murphybarb** [comment]
Functionality rocks. 

Treatment of left hand "Feature" container will be addressed in the design review. Moving to done.
