### ISSUE TITLE
Subscribe feature

### ISSUE THREAD

**Issue by alex-418** [BCcampus/bcc-sage#159]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

## Feature Request

Looks like we're creating a button that points to https://confirmsubscription.com/h/d/97F887551C7932F2

Campaign Monitor does have an API if further integration is necessary https://www.campaignmonitor.com/api/subscribers/

It may be the case that we can easily embed the form on our own site. Looking to @murphybarb to investigate the settings in campaign monitor.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/bcc-sage/pull/171 
validated via footer and https://helga.bccampus.ca/wp/bcc/news/
