### ISSUE TITLE
related events component

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#160]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

## Feature Request

Related events are limited to 4 and are found on a few landing pages. They are limited in scope to tags, which are the value of the page they occupy. They do not include an image, but have a date (of event) and title.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/bcc-sage/commit/876201eff4cd7688d1415d1ed8fc9b9ea84e13e5

![image](https://user-images.githubusercontent.com/2048170/45118151-737b8980-b10c-11e8-95d7-ae4b87da96f9.png)

**Comment by bdolor** [comment]
can be validated on https://helga.bccampus.ca/wp/bcc/topics-of-practice/
https://helga.bccampus.ca/wp/bcc/grants-calls-for-proposal/
https://helga.bccampus.ca/wp/bcc/about-us/
https://helga.bccampus.ca/wp/bcc/projects/

**Comment by murphybarb** [comment]
OMG. Apologies for being a bonehead. Looking at this now.

**Comment by murphybarb** [comment]
The screen cap provided above is different from the view at the URLs provided: 
- the screen cap contains boxes around the text. Boxes are not used in the links above 
- the padding is different in the screen cap than the links above

Are the URLs above intended to look exactly like the screen cap posted above?

**Comment by bdolor** [comment]
please ensure your browser cache is cleared.

**Comment by murphybarb** [comment]
I cleared cache. Still the same. I attached an image of what I see. 

I can provide styling info based on what I see at the URLs. Is that how you'd like me to proceed? 
Thanks! 
![screen shot 2018-09-05 at 3 14 47 pm](https://user-images.githubusercontent.com/11672469/45124293-93b44400-b11e-11e8-9d16-6411cdf3b3b8.png)

**Comment by murphybarb** [comment]
Hi @bdolor 

The content looks ok, that is approved. 

The styling needs adjusting to match the design layout. I have provided a screen capture containing padding and line height information. 

![screen shot 2018-09-07 at 10 41 27 am](https://user-images.githubusercontent.com/11672469/45234453-a055ab00-b28a-11e8-9ce2-c1189767ddad.png)

**Comment by bdolor** [comment]
expressing padding in pixels will work for a desktop view with full screen size, but breaks down quickly as screen size diminishes. Similarly, fixing box height at 175px works for titles of a certain length but breaks down quickly with variations in title length. I won't be able to commit to these changes, but am happy to work towards replicating look and feel as best we can.

**Comment by murphybarb** [comment]
Thanks for explaining @bdolor, I thought I was being helpful in providing some type of guideline. 
I'm happy with **"work towards replicating look and feel as best we can."**

Moving to "done", design details to be addressed in design review.
