### ISSUE TITLE
category/taxonomy component 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#163]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

## Feature Request

New landing page: Create 2 components that displays a list of 4 most recent blog posts that belong to a specific category. They need to have an image, a date, a title and the category name.

**Comment by bdolor** [comment]
can be validated at any and all of 
- https://helga.bccampus.ca/wp/bcc/category/edtech/edtech-demo/ 
- https://helga.bccampus.ca/wp/bcc/category/general/
- https://helga.bccampus.ca/wp/bcc/category/event-recap/

**Comment by murphybarb** [comment]
@bdolor 

The functionality of how the list of results displays is great. I realize some things will be addressed when the the style guide is applied. Want to confirm that all the items I see as styling will be addresses: 

- the page matches the [design layout ](https://cloud.bccampus.ca/index.php/apps/files/?dir=/*Current%20Jobs/283%20Web%20Consolidation%20Project/Visual%20Design/BCcampus.ca/BCcampus.ca%20%E2%80%93%C2%A0Assests%20for%20DevOps/Templates%20(x11)/10.%20News%20category%20page&fileid=2957525#/*Current%20Jobs/283%20Web%20Consolidation%20Project/Visual%20Design/BCcampus.ca/BCcampus.ca%20%E2%80%93%C2%A0Assests%20for%20DevOps/Templates%20(x11)/10.%20News%20category%20page/10.%20News%20Category-desktop.jpg), with the categories, newsletter sign up and, etc in the right hand sidebar

- listing of 4 items only 

- has "previous" and "next" options 

- regarding text in blue banner "For the “news” section the title will remain as “News” in the blue banner, in the entire section."
