### ISSUE TITLE
Tabs Component

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#164]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

## Feature Request

the current events plugin doesn't allow tab features that are outlined in the mock ups. Barb will take a look at what features are available in a 'pro' type scenario. The other option that was discussed was divorcing the tab content from the event and finding a unique identifier to marry the two.

**Comment by murphybarb** [comment]
@bdolor 

I did some investigation, I don't think there is much here to help us achieve the tabs on the individual event page. Pro appears to be more geared towards promoting your event than modifying the style/design.  

- The plugin site: https://wordpress.org/plugins/all-in-one-event-calendar/
- The plugin appears to have add ons, but nothing to modify the style: https://time.ly/wordpress-calendar-plugin/add-ons/
- Pro: https://time.ly/plan

**Comment by alex-418** [comment]
@murphybarb I was able to make some progress in this, and came up with a strategy with @bdolor that could work to accomplish this. The two constraints are as follows: 
- The tabbed event content is static (comes from the specific event page content editor) 
- You're okay with a short-code to use as a delimiter to separate the content of each tab

**Plugins:**
I tested two plugins that could help us accomplish this functionality, the results were favorable. I'm optimistic that we could get this functionality in an event, although there's a theme conflict to overcome with the one I liked [the most](https://wordpress.org/plugins/tabby-responsive-tabs/). 

**Better solution:**
A better strategy would be to create our own short-code that uses [jQuery UI tabs](https://jqueryui.com/tabs/) as jQuery and it's UI are part of WordPress core. 

Here's the results of my tests, please let me know if this could work for your needs: 

**Authoring the tabs inside the event editor:**

![event_tabs](https://user-images.githubusercontent.com/17072191/45579661-6b26fb00-b83e-11e8-83dc-c3bf428ad0e1.png)

**Display of the tabs on a single event page:** 

![single_event](https://user-images.githubusercontent.com/17072191/45579662-6cf0be80-b83e-11e8-9859-cad233f0212b.png)

**Comment by murphybarb** [comment]
Can you direct me to where I can copy and paste the shortcode above to test this out on the dev site?

**Comment by bdolor** [comment]
go to a single events page and in the description area is where, I believe, you would put the shortcode.

**Comment by murphybarb** [comment]
@bdolor 

I've copied and pasted the following (as seen above) and get it to work. Not sure what I'm doing wrong: 

[tabby title="test"]

First tab content

[tabby title="second tab"]

second tab content

[tabbyending"]


You can see the [test event here](https://helga.bccampus.ca/wp/bcc/event/symposium-2018-scholarly-teaching-learning-in-post-secondary-education-2/?preview_id=698908&preview_nonce=b504e8c5f7&_thumbnail_id=-1&preview=true)

**Comment by murphybarb** [comment]
Proceed with: 

Better solution:
A better strategy would be to create our own short-code that uses jQuery UI tabs as jQuery and it's UI are part of WordPress core.

Here's the results of my tests, please let me know if this could work for your needs:

**Comment by alex-418** [comment]
Proceeding creating our own short-code to add tabbing functionality.

**Comment by ehbeattie** [comment]
Duuuuuuuudes, I freakin' love these tabs!! Is there any possible way to make the sections pop out a little more to make it more obvious that there's more to click through? 

<img width="528" alt="screen shot 2019-01-23 at 1 08 57 pm" src="https://user-images.githubusercontent.com/44707412/51637285-332c7480-1f10-11e9-8bd9-9d79ca8f534a.png">

**Comment by bdolor** [comment]
@ehbeattie you'll need to clarify what you mean by `make the sections pop out a little more`...colour, size...animation of a muskrat... :pop:  Depending on what it is, we might want to look at capturing the work of that in another ticket.

**Comment by ehbeattie** [comment]
Although I do love the animation of a muskrat as much as the next, I was more hoping for something similar to the mock-up with greys or heavier contrast to stand out a little more for our more visually impaired users.

**Comment by ehbeattie** [comment]
That being said, yes, it can be in another ticket if you'd like to publish this.

**Comment by bdolor** [comment]
ah right then...I see you don't like muskrats...perhaps, since it is an accessibility concern the work could be (is already) investigated/captured in https://github.com/BCcampus/bcc-sage/issues/220

**Comment by ehbeattie** [comment]
Perfect. Validated.

**Comment by kkilbey** [comment]
Muskrats or no, these are some snazzy tabs indeed. Since the accessibility concerns will be addressed in ticket #220, I'll move this to Done.

**Comment by dshaykewich** [comment]
Tabs plugin documentation: https://wordpress.org/plugins/tabby-responsive-tabs/
