### ISSUE TITLE
Events: sponsors component

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#165]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

## Feature Request

On the individual event page template design mockup there is a component that is identified as sponsors (see attached for location reference)...no further details have been provided. Similar to the tabs, this is not out of the box functionality and options will have to be explored. 

**What is the expected or desired behavior?**
Some events, not all events, will require this space to upload and display sponsorship logos. It would be ideal to be able to "show" or "hide" this section. 

![image](https://user-images.githubusercontent.com/2048170/44053177-ac7eb8d6-9ef3-11e8-8571-27dc71076c3d.png)

![bccampus-events-content-desktop-final_1_](https://user-images.githubusercontent.com/11672469/47129705-4661e100-d24b-11e8-8994-b83d28149162.png)

**Comment by ehbeattie** [comment]
I feel like this would be resolved within the tabs. Closing it as a separate task.
