### ISSUE TITLE
Embed newsletter subscription form the form on our own site

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#172]
## Submit a feature request or bug report

- [X] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

## Feature Request

Embed newsletter subscription form the form on our own site

Campaign Monitor does have an API if further integration is necessary https://www.campaignmonitor.com/api/subscribers/

It may be the case that we can easily embed the form on our own site.

Subscription button currently points to https://confirmsubscription.com/h/d/97F887551C7932F2

 @murphybarb to investigate the settings in campaign monitor and providing embed code.

**Comment by alex-418** [comment]
@murphybarb please send login information

**Comment by murphybarb** [comment]
Hey Alex, 

Here’s the login info for campaign monitor  

https://bccampus.createsend.com/login
bmurphy@bccampus.ca
seymour555

**Comment by bdolor** [comment]
this is a public website. please don't paste login info here.

**Comment by alex-418** [comment]
@murphybarb Created the "Subscribe" page on helga. 
https://helga.bccampus.ca/wp/bcc/subscribe/
This page is required along with assigning the "Subscribe page template" to it. 

Two other pages that need to be created in prod are: 
bccampus.ca/subscription-successful
bccampus.ca/subscription-confirmed

These settings can be updated at https://bccampus.createsend.com/subscribers/subscribeProcess.aspx?listID=97F887551C7932F2 (in case you wanted to change the name/location of the pages): 
![settings](https://user-images.githubusercontent.com/17072191/45574313-7ec56800-b824-11e8-8f70-29dc4e63aeb4.png)

**Comment by alex-418** [comment]
@murphybarb Please note we rolled this one back, so it can't be validated until the pages are created on production and the settings updated as per my screenshot above.
