### ISSUE TITLE
Grants and proposals child pages 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/bcc-sage#186]
Make the child pages show up in this landing page under the correct parent page (as per Barbs e-mail)

**Comment by alex-418** [comment]
Remove hardcoded values for parent page ID's, move these as an option.

**Comment by alex-418** [comment]
Completed in #191

**Comment by alex-418** [comment]
@murphybarb Created the "Subscribe" page on helga. This page is required along with assigning the "Subscribe page template" to it. 

Two other pages that need to be created in prod are: 
bccampus.ca/subscription-successful
bccampus.ca/subscription-confirmed

These settings can be updated at https://bccampus.createsend.com/subscribers/subscribeProcess.aspx?listID=97F887551C7932F2 (in case you wanted to change the name/location of the pages): 
![settings](https://user-images.githubusercontent.com/17072191/45574313-7ec56800-b824-11e8-8f70-29dc4e63aeb4.png)

**Comment by alex-418** [comment]
@murphybarb Please note there's new settings for the grants page (This is where you can enter the post ID of the parent pages for Open and Closed proposals).

![grant_settings](https://user-images.githubusercontent.com/17072191/45575199-80445f80-b827-11e8-96eb-3b7a5d534228.png)

**Comment by murphybarb** [comment]
@bdolor I'm using page IDs in the URLs (see attached) to test having different pages appear. It doesn't appear to be working, I'm I using the wrong page ID? 

![screen shot 2018-10-01 at 1 01 04 pm](https://user-images.githubusercontent.com/11672469/46312497-17285000-c57a-11e8-98db-efe6bebe6b2d.png)

**Comment by bdolor** [comment]
Content displaying is dependent on the parent-child relationship. So if the ID of the page does not have any children, nothing will appear.

**Comment by murphybarb** [comment]
@bdolor can you direct me on how I would do the following: 

How would we insert the following page under "Open Calls for Proposals": 
https://helga.bccampus.ca/wp/bcc/bccampus/events/symposium-2018-all-pages/?preview_id=698556&preview_nonce=a4bb80d052&_thumbnail_id=698748&preview=true

How do we enter the page ID's in the customization settings if there is more than one that needs to appear there? I tried with a comma and all the child pages appeared 

How do we move "4.1 BCcampus Learning Access Program for Educators (LAP-E)" from under "Grants Currently Offered" to "Currently Closed Opportunities". That is one that will open and close often.

**Comment by bdolor** [comment]
The limitations that we're working with under a parent-child relationship are:
1. All items must be a 'Page' (not an 'Event')
2. There can only be one Parent.
3. Moving one child page from the parent 'Grants Currently Offered' to 'Currently Closed Opportunities' requires changing the relationship of the child page, to the other parent.

**Comment by murphybarb** [comment]
1. we need to be able to add an event here, as calls for proposals most times will come from an event. 
2. ok, thanks for explaining
3. Looking at the dashboard I see how you set this up, but see what I think might be an issue. Maybe I'm wrong though? 'Grants Currently Offered' and Currently Closed Opportunities' are not assigned parent pages. When you assign them the parent page of '4.0 Grants and Calls for Proposal', which would be the parent page, the child pages appear in the 'Grants Currently Offered' section, which we do not want.

**Comment by bdolor** [comment]
1. I believe we've talked about the limitations around this already, forgive me if this is running over old ground. The last correspondence (Aug.16) that formed the basis of what we were building from: 

> So, if I recall, you needed me to confirm if the “open calls for proposals” content on the G&CFP landing page would be pulled exclusively from the events pages/section/calendar plugin. No, the content to dynamically appear in the “open calls for proposals” container would also come from child pages of “open calls for proposals”. 

Probably better to address in a discussion.

2. great
3. Probably better to address in a discussion.

**Comment by murphybarb** [comment]
Sounds like a great plan. When is good for you to chat on Tuesday? I'm available anytime, I have not meetings scheduled. Thanks!
