### ISSUE TITLE
Update page/publish notifications email address

### ISSUE THREAD

**Issue by jgrajkowski** [BCcampus/bcc-sage#196]
The several people on the Communications@bccampus.ca distribution list don't need to get allll the updates every time a page is published... but just a few people do.

The new alias "commupdates@bccampus.ca" has been generated to direct messages to fewer staff and allow the recipients to be managed in Zimbra Admin/without Dev.

**Please update this notification setting to the new address: commupdates@bccampus.ca in the new theme's settings.**

If there's any capacity to make this change to the other sites identified below to minimize the messages to the other Communications staff while the content is being transitioned, great, though the New BCcampus.ca™ is the priority.

Original request from Erin:
At the moment, we have notifications being sent to us for all updates that happen on the BCcampus WordPress sites (BCcampus, OpenEd, ETUG, etc.). Could you please change them from going to Communications@BCcampus.ca to just Kate, Barb and I?

**Comment by bdolor** [comment]
this change is reflected in tomorrow's rollout.

**Comment by bdolor** [comment]
email notifications have been turned off by request, RC only notifications via https://github.com/BCcampus/bcc-sage/commit/7eee9e9f5e6b8ee66f9563d826157098d02f965e
