### ISSUE TITLE
topics of practice and projects functionality on homepage

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#208]
## Submit a feature request or bug report

- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---
Topics of Practice need to pull in the feature image from the topics of practice and linked back to the page. Also, on the events page EdTech Demos and Facilitating Online Learning need the same treatment. 

**What is the current behavior?**

Placeholder image and no link back

https://helga.bccampus.ca/wp/bcc/events/
https://helga.bccampus.ca/wp/bcc/

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/bcc-sage/commit/913d5451fa84c727e0ca19c21fc60eb6b72a2143 and https://github.com/BCcampus/bcc-sage/commit/64cf83049a8b83a148c3f2e3c35c555e76e079e4 

Current constraints around edtech and flo event categories exist because of what they are (they are unlike other featured elements). These are a collection of event categories, and don't lead back to a parent page where featured images can be set. Currently, those two elements can display featured images that are set in the events landing page, and if none exists, then a default image.

**Comment by murphybarb** [comment]
To confirm, the only way to display two different images in the edtech and flo event categories, other than the featured image, is to insert them into the template? If so, shall I move this issue to "done" and create a new issue to insert images in the edtech and flo?

**Comment by bdolor** [comment]
correct.

**Comment by murphybarb** [comment]
Moving to 'done' creating new issue to insert images into edtech and flo.
