### ISSUE TITLE
users need ability to change header image  on parent page

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#209]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

header image is static and hard coded into the theme. 

The same header image (image located at the top of each page that extends full width) displays throughout the site . 

**What is the expected or desired behavior?**

on each of the parent pages, users need a way to periodically update the header image 

Each parent page displays a different image that cascades to child pages. 

Parent pages are: 
- About Us
- Projects 
- Topics of Practice 
- Grants and Calls for proposals 
- Events

## Feature Request

**Please provide use cases for changing the current behavior:**

Spec for original design 

**Other relevant information:**
Would like option for content creators to update these images and not DevOps. If time does not permit for that option for launch, will move request for content creators to update images to backlog  and DevOps can insert images into template.

Header images are located in NextCloud: https://cloud.bccampus.ca/index.php/apps/files/?dir=/*Current%20Jobs/283%20Web%20Consolidation%20Project/Photos%20for%20site%20/*FINAL%20PHOTOS/Page%20Headers%20images&fileid=3100420

**Comment by stargraphicdesign** [comment]
Additional information:
- It's intended that the child pages inherit the parent's header image.

**Comment by alex-418** [comment]
Use the pages featured image to pull in the banner.

**Comment by alex-418** [comment]
Featured images are now used as banner image on all landing page templated.

**Comment by alex-418** [comment]
All banner images were added to landing page templates as "featured images" thanks @ehbeattie for creating one so quickly for research page.

**Comment by alex-418** [comment]
All pages to have a banner image, use default image if there's no featured image set.

**Comment by alex-418** [comment]
@ehbeattie completed via https://github.com/BCcampus/bcc-sage/commit/25836a3657be1fbb88c3937b6e73c63ed8d1aafb but the placeholder image currently is not the right size. As you can see in a generic page. Can you please provide a placeholder image I can use to replace this one?
