### ISSUE TITLE
copy for grants and calls proposal boxes

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#211]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

copy is being pulled from the parent pages they are attached to

**What is the expected or desired behavior?**

The descriptions in the box area needs to be text that is manually entered/different than the copy of the page.

**Comment by bdolor** [comment]
@murphybarb - looking to you for copy

**Comment by bdolor** [comment]
some of this is resolved via https://github.com/BCcampus/bcc-sage/commit/a0ee75ac749cdfe9c7bb0f8cd9ccbedadc3ac740 though there are many details that have been added to this issue that require discussion and broken down into smaller chunks.

**Comment by murphybarb** [comment]
Ok, sounds good. 

Did you want me to break down into smaller chunks then discuss or discuss and breakdown together? Thanks!

**Comment by bdolor** [comment]
together is better - so we avoid making assumptions.

**Comment by murphybarb** [comment]
As discussed in the stand up meeting Oct. 11, we will break this down into smaller chunks at the planning meeting for the next sprint.
