### ISSUE TITLE
Header: "Display preferences" tab visual change

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#214]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

Display preferences functionality can be accessed via a tab at the top of every page. 

![image](https://user-images.githubusercontent.com/2048170/46554831-587c7080-c896-11e8-8133-94c412c297cc.png)

**What is the expected or desired behavior?**

Instead of a tab, left align text with a computer icon 

![image](https://user-images.githubusercontent.com/2048170/46554805-44d10a00-c896-11e8-9f95-3542d6499d39.png)

**Comment by murphybarb** [comment]
Note: Attached screen capture for visual reference. 

Desired outcome: change styling and position of the "+show display preferences" tab located top, right in the header. 

**Are we able to modify apply the preferred styling?:** 

Preferred styling – remove ‘tab’ treatment around text, move text down, above search box field, 
apply same grey as “Help” and “Contact Us”. 

If we are able to apply the perferred styling, the computer icon in the attached reference will be supplied. 

If we are not able to apply the preferred styling, align right-hand edge of the the "+show display preferences" tab with the righ-hand edge of the "Search" entry field. See attached for reference of alignment. 

**Styling Reference:** 
![screen shot 2018-10-12 at 12 53 00 pm](https://user-images.githubusercontent.com/11672469/46891164-df44c680-ce1d-11e8-8615-bec44e93b606.png)

**Alignment Reference:** 
![screen shot 2018-10-12 at 1 04 16 pm](https://user-images.githubusercontent.com/11672469/46891648-5fb7f700-ce1f-11e8-9368-95a05d8492e3.png)
