### ISSUE TITLE
update header logo 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#215]
## Submit a feature request or bug report

- [ ] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

Site logo has been updated 

**What is the expected or desired behavior?**

New logos have been generated and need to be in place.

**Comment by stargraphicdesign** [comment]
For the record, new logo in the **header** only, the footer keeps the old one.
