### ISSUE TITLE
Header: style the open state of the Display Preferences

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#217]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

The open state of Display Preferences tab comes with its own style.

**What is the expected or desired behavior?**

Desired behaviour is that the open state of Display Preferences is more in line with the theme styling.

Are we able to change the current styling of the "show display preferences" to look like the attached suggested design? If so, the monitor icon shown in the attached can be supplied. 

![screen_shot_2018-10-17_at_5_57_27_pm](https://user-images.githubusercontent.com/11672469/47125152-a5692b00-d236-11e8-8a9b-5bebb68839d6.png)

**Comment by stargraphicdesign** [comment]
- Do we have the ability to style this?
- If so, I will provide a mockup. Just looking for a yes or no at this point.

**Comment by bdolor** [comment]
yes, we own all the stylesheets https://github.com/BCcampus/bcc-sage/tree/dev/lib/infusion/src/framework/preferences/css
