### ISSUE TITLE
mega menu problems

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#222]
## Submit a feature request or bug report

- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

- featured image seems only to work by creating a sample page.
- hovering over the image in the mega menu that's the only way to create three columns
- only way to have title on the image is to build it right into the image

**What is the expected or desired behavior?**

- we want images to display the title of their parent page without needing to create an image that does that. 
- we want no background colour on hover. 
- need to investigate/break the dependency of an image to a sample page. 
- images should be clickable to the parent page

**Comment by bdolor** [comment]
- featured image does not require a sample page to be created, it can use the featured image of the parent page. 
- as a result, clicking on the image takes one to the parent page.
- background colour change on hover has been removed via https://github.com/BCcampus/bcc-sage/commit/f82e4fdf933816fdcc3634ec74bc12e6d230acf1

![image](https://user-images.githubusercontent.com/2048170/46687330-87088d00-cbaf-11e8-8fe2-6c81c30e1d22.png)

- likely possible to *not* require that featured images have the purple banner and title 'baked into' the image, but likely not under current time constraints. images best served at 260px wide.

**Comment by bdolor** [comment]
@murphybarb - for validation, please consider the two options for featured images. 

1. create 6 featured images at 260px wide with title and purple banner baked into the image.
2. use 6 featured images without purple banner and title similar to how 'topics of practice' is currently being displayed in the megamenu. 

![image](https://user-images.githubusercontent.com/2048170/46689545-03519f00-cbb5-11e8-8d57-421dbdda6cc7.png)

**Comment by stargraphicdesign** [comment]
I agree with not putting the link into the image. What we've ended up with is definitely not what I intended, I think its a huge usability issue to have the only link to the parent page be an image, which was also not my intention. 

Please make sure that blue colour is the right HEX# (for the record, all the mega menu links were supposed to be black like the parent nav)

**Comment by stargraphicdesign** [comment]
Also, I think that Parent link should be above the photo, i feel like its getting lost in the bottom left corner

**Comment by bdolor** [comment]
There are two links to the parent page
- one is the image
- the other is the title

**Comment by murphybarb** [comment]
@bdolor 

- Agree with suggestion of not using images with purple banner 'baked' in. The mega menu Images are currently being updated without banner included.   
- I agree with Jessica regarding placement of the link. Can we move the parent link above the photo?
- Please make sure that blue colour is the right HEX# (all the mega menu links were supposed to be black like the parent nav)

- also, regarding the styling of the text in the drop down menu – all pages should be bold with child pages below regular text. 

The text styling in the mega menu would be like so: 

- 1.0 - all bold 
- 2.0 - All bold, except 2.4.1 to 2.4.4, 2.5.1 to 2.5.3, 2.8.1 
- 3.0 - all bold 
- 4.0 - all bold, except 4.4.1 to 4.4.4 
- 5.0 - all bold 
- 6.0 - all bold

**Comment by bdolor** [comment]
Is the colour of links not covered in https://github.com/BCcampus/bcc-sage/issues/212 ?

**Comment by bdolor** [comment]
as per discussion, the only menu items _not_ bold are grandchildren.
