### ISSUE TITLE
Mobile: Related News and Events

### ISSUE THREAD

**Issue by stargraphicdesign** [BCcampus/bcc-sage#223]
## Submit a feature request or bug report

- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

https://helga.bccampus.ca/wp/bcc/bccampus/projects/  (and similar page templates)
- News and events articles aren't lining up to the grid as expected 

**What is the expected or desired behavior?**
- Align them as per the mockup
- News featured article needs bottom margin
- Events articles need bottom margin

Mobile (needs layout adjustments as well as grid alignment):
![screen shot 2018-10-05 at 4 10 00 pm](https://user-images.githubusercontent.com/1656362/46563941-24667700-c8b9-11e8-844e-4a8a0f3edb15.png)
Tablet (this version i'm okay with the layout, but the articles do need to line up):
![screen shot 2018-10-05 at 4 05 18 pm](https://user-images.githubusercontent.com/1656362/46563831-8ecae780-c8b8-11e8-9ad1-04e8eebc4d45.png)
Mobile Mockup:
![bccampus-projects-mobile-final](https://user-images.githubusercontent.com/1656362/46563901-f123e800-c8b8-11e8-9027-386a5dc928de.jpg)

**Comment by bdolor** [comment]
related news and events have been addressed
