### ISSUE TITLE
*Mobile: Navigation and Sub-Navigation

### ISSUE THREAD

**Issue by stargraphicdesign** [BCcampus/bcc-sage#224]
## Submit a feature request or bug report

- [ ] This is a feature request
- [X ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

- Duplicate hamburger menus
- Show display preferences takes up too much screen real estate and should be hidden
- Search should be an icon
- Sub navigation "in this section" needs styling

**What is the expected or desired behavior?**
- Styled as per mockup attached
- clicking the search button or the hamburger menu opens up the mobile menu with all the elements inside it.
---

![current](https://user-images.githubusercontent.com/1656362/46564094-2aa92300-c8ba-11e8-91a7-675c5f7dd709.png)

![mobile-nav](https://user-images.githubusercontent.com/1656362/46564096-2e3caa00-c8ba-11e8-9b1b-2509690bd3f8.jpg)

![bccampus-home-mobile-menuopen](https://user-images.githubusercontent.com/1656362/46564099-30066d80-c8ba-11e8-8b68-aae6330c53cc.jpg)

**Comment by bdolor** [comment]
ready for validation — improvements have been made from a mobile perspective. Please ensure to refresh/clear browser cache.
