### ISSUE TITLE
Mobile: Tablet view gets full width content area

### ISSUE THREAD

**Issue by stargraphicdesign** [BCcampus/bcc-sage#225]
![screen shot 2018-10-05 at 4 19 03 pm](https://user-images.githubusercontent.com/1656362/46564132-70fe8200-c8ba-11e8-8935-a5761ba1cec6.png)

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/bcc-sage/commit/688e79e1df7425f8da9927081afb50c191954e5c
