### ISSUE TITLE
*Mobile: Homepage layout

### ISSUE THREAD

**Issue by stargraphicdesign** [BCcampus/bcc-sage#226]
https://helga.bccampus.ca/wp/bcc/

mobile layout on home needs adjusting for alignment, placement and spacing

Current:

![screen shot 2018-10-05 at 4 20 54 pm](https://user-images.githubusercontent.com/1656362/46564222-deaaae00-c8ba-11e8-9cc3-5b2694a972b0.png)

Mockup:

![bccampus-home-mobile-final](https://user-images.githubusercontent.com/1656362/46564215-d5214600-c8ba-11e8-9201-dfb3c95f13f5.jpg)

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/bcc-sage/commit/b34cabc22ada193210417d527b218206d1855599

**Comment by murphybarb** [comment]
are we able to line up the following on mobile view. See attached for reference, the left and right edges of different groupings of containers do not align. 

![screen shot 2018-10-17 at 6 36 44 pm](https://user-images.githubusercontent.com/11672469/47126075-ba948880-d23b-11e8-9def-9530a7c4c935.png)
![screen shot 2018-10-17 at 6 36 36 pm](https://user-images.githubusercontent.com/11672469/47126076-ba948880-d23b-11e8-81a5-fe50a4a925d7.png)

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/bcc-sage/commit/0fb53db64405b6265a9a133d593ee1e145e418f9

**Comment by ehbeattie** [comment]
The alignment and spacing look lovely for the items from **Topics of Practice** and down, but the height of the slider images are much too large. It took me three scrolls to get to the next option. For reference: I'm using an iPhone 6 with iOS 12.1. 

Here are some images of said scroll: 

![image1](https://user-images.githubusercontent.com/44707412/47932617-5efb0980-de8f-11e8-8020-28cb8ac46aa7.png)
![image2](https://user-images.githubusercontent.com/44707412/47932618-5efb0980-de8f-11e8-991e-3db59b3c9bea.png)
![image3](https://user-images.githubusercontent.com/44707412/47932619-5efb0980-de8f-11e8-926f-fa95a2ca5213.png)

**Comment by ehbeattie** [comment]
@bdolor - yes, yes I am.

**Comment by bdolor** [comment]
I had @dshaykewich check on his phone and it looks long but not unruly. May be isolated/specific to the phone browser version you're working with.

**Comment by ehbeattie** [comment]
I'd like to revisit this one as the header/slider image is very large on my iPhone.
