### ISSUE TITLE
Mobile: News Article

### ISSUE THREAD

**Issue by stargraphicdesign** [BCcampus/bcc-sage#227]
https://helga.bccampus.ca/wp/bcc/the-bccampus-201617-annual-review/

News articles, under the content area:
- the Related Stories and Recent News need to line up
- The Related Stories need a layout adjustment to stack like the mockup

![screen shot 2018-10-05 at 4 23 26 pm](https://user-images.githubusercontent.com/1656362/46564299-4bbe4380-c8bb-11e8-9229-993a8603aa85.png)

![bccampus-news-content-mobile-final](https://user-images.githubusercontent.com/1656362/46564301-4e209d80-c8bb-11e8-971f-0c012fbe1451.jpg)

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/bcc-sage/commit/e2b378defeca1abd2f3542c350e0123801edc22e

**Comment by murphybarb** [comment]
Related Stories section: 

Current state on tablet view:
Excess white space after last line of text and bottom of container, see attached for reference 

Desired state on tablet view: 
Reduce amount of white fter last line of text and bottom of container, see original design mock up above for reference  


![screen shot 2018-10-17 at 6 26 58 pm](https://user-images.githubusercontent.com/11672469/47125801-4c02fb00-d23a-11e8-9ab5-263d597804fd.png)
