### ISSUE TITLE
*Header Area: spacing and alignment – logo, top nav  

### ISSUE THREAD

**Issue by stargraphicdesign** [BCcampus/bcc-sage#228]
## Submit a feature request or bug report

- [ ] This is a feature request
- [X ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

It doesnt match the design

**What is the expected or desired behavior?**
see mockups below
- The display preferences thing has been downplayed, it uses the same grey as the top nav for the text link

- I'm showing the new search box area that I had included in the feedback doc, with one change being the blue icon. I didn't want it to be the same grey as the Display Preferences Icon. Rounded corners need to be removed.

- My goal here is to remove all spacing possible between the bottom of the logo and the actual nav links, so it'll still appear close to where I intended it to go.

![bccampus-home-newheader](https://user-images.githubusercontent.com/1656362/46681775-d2676f00-cba0-11e8-85c3-c97f1c036fcc.jpg)
![guidelines](https://user-images.githubusercontent.com/1656362/46681776-d2676f00-cba0-11e8-9c68-70b2513d6551.png)

**Comment by murphybarb** [comment]
This task contains 3 requests. 2 that are covered in issues #214 and #216. 

I will update this task to contain the 1 issue not covered in #214 and #216 (the placement of the logo in the header).

**Comment by murphybarb** [comment]
Desired result of header area: 
1. Align the baseline of the text "BCcampus" in the logo, the baseline of the text top navigation ("Find an Open Textook", "open.bccampus.ca", "Help", "Contact Us" and baseline of the word 
"Search" in the search field to the same baseline. As seen in the attached screen capture 
2. Remove white space between the bottom of the the "BCcampus" logo and the the top of the text in the main navigation bar, so it'll still appear close to where I intended it to go.

Note: styling of the search box is addressed in #216. Styling and alignment of the "+show display preferences" is addressed in #218.

**Reference for 1**
![screen shot 2018-10-12 at 12 21 43 pm](https://user-images.githubusercontent.com/11672469/46889874-e36ee500-ce19-11e8-96ae-090cb3145523.png)

**Reference for 2**
![screen shot 2018-10-12 at 12 31 25 pm](https://user-images.githubusercontent.com/11672469/46890191-d9011b00-ce1a-11e8-86d4-066a0b8399f9.png)
