### ISSUE TITLE
*Homepage Events Images

### ISSUE THREAD

**Issue by stargraphicdesign** [BCcampus/bcc-sage#229]
## Submit a feature request or bug report

- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

The Events images under Upcoming on the homepage are not displaying correctly

**What is the expected or desired behavior?**

- They need a css _background-cover_ applied to them in order for them to scale nicely
- Please also apply a _center center_ positioning

---
![screen shot 2018-10-09 at 9 15 23 am](https://user-images.githubusercontent.com/1656362/46683043-098b4f80-cba4-11e8-874e-6a51b488e6c7.png)

**Comment by bdolor** [comment]
been addressed
