### ISSUE TITLE
CSS for Right Sidebar on Pages

### ISSUE THREAD

**Issue by stargraphicdesign** [BCcampus/bcc-sage#230]
## Submit a feature request or bug report

- Here's the css for the styling of the right sidebar menus

- I didn't include the styling for arrows, that's up to you how you want to handle those, with an iconfont or images. The css for those can easily be added to this. If you get some arrows in place I can always provide updated styling.

---

aside#sidebar li.pagenav ul{
  border: 1px solid #d4d4d4;
  margin-top: 1rem; 
}
aside#sidebar li.pagenav ul li,
aside#sidebar li.pagenav ul li:first-of-type,
aside#sidebar li.pagenav ul li:last-of-type{
  margin:0;
  padding: 0;
}
aside#sidebar li.pagenav ul li a{
  display:block;
  padding: 0.7rem 0.6rem;
}
aside#sidebar li.pagenav a:hover{
  background: #ebebeb; 
  color: #009dd6;  
  text-decoration: none;
}
aside#sidebar ul.children {
  border: none !important;
  margin: 0 !important;
  padding: 0;
}
aside#sidebar ul.children li {
  border: none;
  font-weight: normal;
  font-size: 15px !important;
  margin:0;
  padding: 0;
}
aside#sidebar ul.children li a{
  padding: 0.3rem 0.6rem !important;
}
aside#sidebar .current_page_item a{
  color: #52b74e !important;
}

![sidebar](https://user-images.githubusercontent.com/1656362/46685250-df3c9080-cba9-11e8-916e-5a9d50c862f7.jpg)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/bcc-sage/commit/aeb24fc0dda328092db7240964630648603ec975
