### ISSUE TITLE
"Events" section, feature image 

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#231]
## Submit a feature request or bug report

- [ ] This is a feature request
- [x ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**
"Events" page: https://helga.bccampus.ca/wp/bcc/bccampus/events/

The background images for the 'Feature' events (at top of page) and the 'highlight' events (at bottom of the page) are all the same. The events are inheriting the "Events" page featured image.  

The same is happening on in the events section on the home page (the same background image) : https://helga.bccampus.ca/wp/bcc/#

**What is the expected or desired behavior?**

Each 'Feature' event (top of page) and highlight event (bottom of page) should display their own 'featured' image. 

attached image for reference 

---
![events - background image](https://user-images.githubusercontent.com/11672469/46706036-4167b680-cbe7-11e8-8d3a-f95a8cf597c9.png)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/bcc-sage/commit/5080a29830251c133fb5d23764097b6579fff602  duplicate/covered via https://github.com/BCcampus/bcc-sage/issues/208

**Comment by murphybarb** [comment]
@bdolor the two bottom containers on the page "EdTech Demos" and "Facilitating Learning Online" still have the same image, which is the feature image of the parent page. 

There is not a page for these to link to, they are static images. I will have to provide the images for you to place. Unless you have another solution?
