### ISSUE TITLE
*About Us - link productes 404 error

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#232]
## Submit a feature request or bug report

- [ ] This is a feature request
- [X ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

On the "about us" page: https://helga.bccampus.ca/wp/bcc/bccampus/about-2/
In "Related Events" section, below "Related News", the “View all events” link produces a 404 error 

**What is the expected or desired behavior?**

"View all events" should link to https://helga.bccampus.ca/wp/bcc/bccampus/events/

---

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/bcc-sage/commit/4103356d00a72c712bb6c7adec92b5d78a07fed7
