### ISSUE TITLE
*Individual event pages - 'featured' image appears in content area of page

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#233]
## Submit a feature request or bug report

- [ ] This is a feature request
- [X ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

Individual event pages. 

Example : https://helga.bccampus.ca/wp/bcc/event/pressbooks-training-webinar-intro-intermediate-3-2/

When a 'featured' image is indicated for an event, and an image is not inserted within the body content, the 'featured' image appears within the body of the text on the page. 

**What is the expected or desired behavior?**

when an event has a 'featured' specified, the 'featured'  images do not appear within the content of the event page, only to display dynamically where required throughout the site.

**Comment by bdolor** [comment]
this was just a checkbox in the plugin settings: 

![image](https://user-images.githubusercontent.com/2048170/47882066-71206d80-dde5-11e8-997a-0015a85eb6c6.png)

**Comment by ehbeattie** [comment]
This looks good and we can mark this as done, but, just to clarify, is this something we can toggle between if an event does happen to have a feature image we'd like included?

**Comment by bdolor** [comment]
It is a global setting so would have an all or nothing effect on events.
