### ISSUE TITLE
Individual event - styling of content does not match rest of site 

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#234]
## Submit a feature request or bug report

- [ ] This is a feature request
- [X ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

Example: https://helga.bccampus.ca/wp/bcc/event/pressbooks-training-webinar-intro-intermediate-3-2/

Styling of content within individual events does not match rest of site. 

**What is the expected or desired behavior?**

The text styling of individual events matches the rest of the site. 

---

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/bcc-sage/commit/75a42b6bc0199942e245e03cce44674edb06d026 possibly also related to https://github.com/BCcampus/bcc-sage/issues/210 and https://github.com/BCcampus/bcc-sage/issues/233
