### ISSUE TITLE
Events page breadcrumbs 

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#235]
## Submit a feature request or bug report

- [ ] This is a feature request
- [X ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**
Example: https://helga.bccampus.ca/wp/bcc/event/edtech-demo-crowdmark/

“Events” section, in the breadcrumb the "Events" link links to the incorrect page. 

**What is the expected or desired behavior?**

"Events" link in the breadcrumb should link to the 5.0 “Events” landing page, here >> https://helga.bccampus.ca/wp/bcc/bccampus/events/

**Comment by bdolor** [comment]
breadcrumbs rely on the parent-child relationship - all events are children of the parent 'event' (a content type). not something we can change like we can with pages, unfortunately.
