### ISSUE TITLE
News landing page: tagging articles to appear in "Open Education”

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#236]
## Submit a feature request or bug report

- [ ] This is a feature request
- [ X] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**
News landing page: https://helga.bccampus.ca/wp/bcc/news/#

In “Open Education” at bottom of page: 
Not certain how articles have to be tagged with in order to appear in this “Open Education” list

**What is the expected or desired behavior?**

Tag "open education" articles appropriately so to appear in the “Open Education” list

---

**Comment by bdolor** [comment]
posts or pages need to be tagged with 'open education'

https://github.com/BCcampus/bcc-sage/blob/fd3e23f47bcd1125463dc6a82bd1195de8984937/resources/views/partials/tag-open-ed.blade.php#L4

be aware that 'tags' and 'categories' are two separate things.
