### ISSUE TITLE
*News Landing page: Change text 

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#237]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

News landing page: https://helga.bccampus.ca/wp/bcc/news/#

- "Open Textbook" text 
- “view all Open Textbooks news”

**What is the expected or desired behavior?**

- Change "Open Textbook" text to “Learning and Teaching”
- change “view all Open Textbooks news” text to “view all Learning and Teaching news”

What do articles have to be tagged with in order to appear in this newly updated “Learning and Teaching” list

---

**Comment by bdolor** [comment]
updating ticket to a 'feature request' - bug reports describe things that are broken, instead of things that are changing.

**Comment by bdolor** [comment]
category shall heretofore be called 'Learning + Teaching'

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/bcc-sage/commit/14626146ac0c681028e680033e86e922eaf75bdb

**Comment by murphybarb** [comment]
Confirmed – expected or desired behavior achieved:    
-  Changed "Open Textbook" text to “Learning and Teaching”
-  changed “view all Open Textbooks news” text to “view all Learning and Teaching news”

**Discovered issue:** 
I've tagged the following articles with both Learning + Teaching' and 'Open Education' (is this the correct one?) categories to test having them display in the Open Education and Learning + Teaching sections on this page. They won't show up in those sections, what I'm I doing wrong?

- [Test Post 8 – Collaboration: The Key Ingredient for a Sustainable Open Education Movement](https://helga.bccampus.ca/wp/bcc/test-post-8/)
- [Test Post 9 – Citation vs. Attribution](https://helga.bccampus.ca/wp/bcc/test-post-9/)
- [Test Post 10 – Introducing the new BCTLC chairs – collaborative excellence](https://helga.bccampus.ca/wp/bcc/test-post-10/)

**Comment by bdolor** [comment]
you've only discovered the difference between tags and categories, I'm afraid. The test posts listed above belong to categories and the functionality in those areas looks for tags.

**Comment by murphybarb** [comment]
Oh, ok. I thought it was categories, as that's what is referenced above. 

I've tested attaching "Learning + Teaching" and "Open Education" tags to the 3 articles listed above. Still can't get them to display. What I'm I doing incorreclty?

**Comment by bdolor** [comment]
we've been loose with our terms: https://github.com/BCcampus/bcc-sage/issues/236

**Comment by bdolor** [comment]
the only logic currently controlling what shows up is: 
1. how many show up
2. that they have a particular tag

If there are 10 tagged with 'open education' and 3 is the limit, it'll grab 3 off the top. If I had to take a guess this is likely preamble for a request to randomize the tagged content that shows up, yes?

**Comment by murphybarb** [comment]
> If there are 10 tagged with 'open education' and 3 is the limit, it'll grab 3 off the top. If I had to take a guess this is likely preamble for a request to randomize the tagged content that shows up, yes?

Thanks for the explanation. I was only attempting to test is the tags were working. But your explanation makes sense as to why it wasn't working. In any case, I think randomizing the tagged content that shows up makes sense. Can we randomize the content that displays there? 

> maybe should revisit if `tags` still works, and whether or not `categories` is the preferred method for filtering.

I'll go with what you recommend is best practice. I thought we were working with categories for all dynamic content. I've been tracking the categories, and just added these recend tags, [in this document: ](https://docs.google.com/spreadsheets/d/1mXWKGujEMGqyKWX6xI03TvHPzYgXxUkZZZHJlJM8v1w/edit?usp=sharing). The document is in progress...

**Comment by bdolor** [comment]
Categories vs Tags is a content related question...it matters what it is that you're trying to do with the content. Both are taxonomies, but you can start to think of the differences in terms of size: category is a broad grouping and a tag as a more detailed grouping. They are meant to work together and express different things. Functionally, one difference is that categories can have hierarchies, whereas tags cannot. Another functional difference is that categories are mandatory (when publishing, default is 'Uncategorized'), whereas tags are optional.

**Comment by murphybarb** [comment]
We have determined the 6 categories we are using for our news articles: 
1. OpenEd 
2. Learning + Teaching 
3. EdTech
4. Collaborative Projects
5. BCcampus
6. Archives

We are have determined the following categories to display dynamic content: 
- **Homepage** - related to feature news
- **Featured** - related to featured events 
- **Call for Proposals** - related to grants and calls for proposals
- **EdTech** (would like to change this to "EdTech Demo" so not to conflict with the EdTech category. This is not a request, will submit that separately. This is just an FYI) - related to events 
- **Flo** - related to events 

Should we consider using categories and creating a hierachy to display dynamic content or stick with tags to display dynamic content?

**Comment by bdolor** [comment]
These are the only two dynamic elements that use tags. If that wasn't intentional then categories are  better. 

So, the new task(s) that come out of this are to 

1. randomize the display of content and 
2. move from tags to categories and 
3. Update the category label from `open education` to `OpenEd`

**Comment by murphybarb** [comment]
@bdolor 

Can we add: 
1. modify "EdTech" category used for events to "EdTech Demo" - this pulls the EdTech events on the Events landing page. We do not want this to conflict with the "EdTech" category for news articles 

Shall I create a new task (or several) or would you prefer to do it?

**Comment by murphybarb** [comment]
Status: 
> So, the new task(s) that come out of this are to
> 
>     1. randomize the display of content and
issue #265 created 
> 
>     2. move from tags to categories and
issue #266 created
> 
>     3. Update the category label from `open education` to `OpenEd`
included in issue #266 


> Can we add:
> 
>     1. modify "EdTech" category used for events to "EdTech Demo" - this pulls the EdTech events on the Events landing page. We do not want this to conflict with the "EdTech" category for news articles
> 
not required, no action taken.
