### ISSUE TITLE
- Topics of Practice landing page: content should not pull from the page

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#239]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

The content displaying for each topic of practice container is pulling from the individual project page.

**What is the expected or desired behavior?**

We do not want the content to pull from each individual page. We have specific content specifically written to appear to appear in this location and not pull from the page.

Do I provide the content or can I update it?

---

**Comment by bdolor** [comment]
updating to 'feature request' to reflect what is a change request, rather than a reporting of something not working. Since this is dynamic content, another mechanism besides post content needs to be looked at (post metadata, custom fields) to put content owners in control of content.
