### ISSUE TITLE
Topics of practice landing page: one container appears twice, remove one

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#240]
## Submit a feature request or bug report

- [ ] This is a feature request
- [ X] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

https://helga.bccampus.ca/wp/bcc/bccampus/topics-of-practice/

A "3.3 Educational Technology" container appears twice. 

**What is the expected or desired behavior?**

Remove one of the "3.3 Educational Technology" containers, so only one appears 

---

**Comment by bdolor** [comment]
Content related. There are two similarly titled pages. 

![image](https://user-images.githubusercontent.com/2048170/46713602-61f63780-cc0c-11e8-9dfa-11465dd914e5.png)

closing
