### ISSUE TITLE
No Hover State on Page Headers

### ISSUE THREAD

**Issue by stargraphicdesign** [BCcampus/bcc-sage#243]
## Submit a feature request or bug report

- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [x] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

The page headers with the blue background, have a hover to a black background.

**What is the expected or desired behavior?**

There should be no hover state for these since they are not clickable.

---

![screen shot 2018-10-10 at 9 32 21 am](https://user-images.githubusercontent.com/1656362/46751470-86373000-cc6f-11e8-941f-59e623fe7b9b.png)

**Comment by bdolor** [comment]
agreed! thanks Jessica.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/bcc-sage/commit/64cf83049a8b83a148c3f2e3c35c555e76e079e4
