### ISSUE TITLE
Projects Page Featured Images

### ISSUE THREAD

**Issue by stargraphicdesign** [BCcampus/bcc-sage#244]
## Submit a feature request or bug report

- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [x] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

featured images for the projects dont look as they should

**What is the expected or desired behavior?**

- background images should "background-position: center center"
- background images should get a "background-size:cover"
---
![screen shot 2018-10-10 at 1 08 37 pm](https://user-images.githubusercontent.com/1656362/46763172-fb196280-cc8d-11e8-9b1b-bd6b15bb9908.png)

**Comment by bdolor** [comment]
addressed in another ticket
