### ISSUE TITLE
Investigate Mail Poet Plugin: Duplicate EdTech Demo sign up and notifcations 

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#245]
## Submit a feature request or bug report

- [X] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---
**Investiage** what is required, and estimate the time, to duplicate the sign up form and notificaiton for EdTech Demos on the new BCcampus.ca.

**What is the current behavior?**
Reference: Users signs up for EdTech demo notifications [using form here on EdTech](https://edtech.bccampus.ca/edtech-projects/edtech-demo/)

Functions of the Mail Poet plugin on EdTech:  
- users use reg form to sign up for the notification subscrption list 
- Clint sends email notifications to the subscription list informing of upcoming Edtech demos
 
Current Registration form fields are: 
- First name (required information)
- Last name (required information)
- Primary institution (pull down menu) - lists primary institutions + "other", 26 total) 
- email (required information)

Form Button to submit information 
- "Subscribe!" button 

**What is the expected or desired behavior?**

Duplicate the sign up and notifcation process on BCcampus.ca that is currenlty being used on EdTEch. 
The sign up form will live on BCcampus.ca on a page on it's own, not embedded within the content, like it currenlty is on EdTech. There will be a link **"Sign up for EdTech Demonstrations"** from [this page on the new BCcampus.ca](https://bccampus.ca/ed-tech/edtech-demos/) to the new sign up form. 

The EdTech subscription sign up form would be intended to duplicate the look and feel of the [BCcampus newsletter subscription form for the new BCcampus.ca](https://helga.bccampus.ca/wp/bcc/subscribe/?subscribe=
)   

---

## Feature Request

**Please provide use cases for changing the current behavior:**

EdTech website is consolidating into BCcampus.ca.

**Other relevant information:**
This is an investigation of if duplicating the same signup and workflow process on the new BCcampus.ca is possible and the time required.

**Comment by bdolor** [comment]
Steps: 
1. Remove all existing subscribers from bcc site
2. Export users from MailPoet (edtech)
3. Import users to MailPoet (bcc)
4. Create a new 'list' on bcc
5. Add subscribers to the list (bcc)
6. Create new subscription button component in bcc-sage theme
7. Create new page template in bcc-sage theme for custom campaign monitor form
8. Quality assurance that components and form are in the expected places
9. Quality assurance that the workflow and sign up form work as expected.

Assumption is that the newsletter 'template' that goes out is out of scope/covered by mark/comm

Initial estimation is that this is a 'Medium' or 'Big' task...or approx 3-7 hours.

**Comment by bdolor** [comment]
closing, going a different route
