### ISSUE TITLE
Events landing page: EdTech and FLO image placement in template 

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#246]
## Submit a feature request or bug report

- [ x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**
Reference: https://helga.bccampus.ca/wp/bcc/events/

Backgroung images appearing in the "EdTech Demos" and "Facilitating Learning Online" containers (located below the calendar) are displaying 'featured' images that are set in the events landing page, and if none exists, then a default image appears. 

**What is the expected or desired behavior?**

Display two different images in the "EdTech Demos" and "Facilitating Learning Online" containers, other than the page's 'featured' image. The images will have to be inserted into the template. 

---

## Feature Request

**Please provide use cases for changing the current behavior:**

Do not want to display the same images in the "EdTech Demos" and "Facilitating Learning Online" containers **or** to display the 'featured' image of the events landing page. 

**Other relevant information:**

Images will be provided, to come. They will be located in this folder in NextCloud: https://cloud.bccampus.ca/index.php/s/DNZoMgHg8xR8WJX

**Comment by alex-418** [comment]
These were moved to the following page: https://bccampus.ca/events/calendar/

**Comment by alex-418** [comment]
Images have been added and can be seen here https://bccampus.ca/events/calendar/

**Comment by ehbeattie** [comment]
Awesome!!
