### ISSUE TITLE
Images  – header images 

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#248]
## Submit a feature request or bug report

- [ X] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**
The same header image (image located at the top of each page that extends full width) displays throughout the site . 

**What is the expected or desired behavior?**

Each parent page displays a different image that cascades to child pages. 

Parent pages are: 
- About Us
- Projects 
- Topics of Practice 
- Grants and Calls for proposals 
- Events
- News 

---

## Feature Request

**Please provide use cases for changing the current behavior:**

Spec for original design 

**Other relevant information:**
Would like option for content creators to update these images and not DevOps. If time does not permit for that option for launch, will move request for content creators to update images to backlog  and DevOps can insert images into template.

Header images are located in NextCloud: https://cloud.bccampus.ca/index.php/apps/files/?dir=/*Current%20Jobs/283%20Web%20Consolidation%20Project/Photos%20for%20site%20/*FINAL%20PHOTOS/Page%20Headers%20images&fileid=3100420

**Comment by ehbeattie** [comment]
We need a way to set unique banner images for each section of the website. Use the current one as the default image for anything without an assigned banner. Attached will be a number of jpgs, labeled accordingly by section. This photo will also match the photo used in the mega menu. 
![banner-about](https://user-images.githubusercontent.com/44707412/58439968-f3c38f80-808b-11e9-9010-a7852f5dc75e.jpeg)
![banner-contact](https://user-images.githubusercontent.com/44707412/58439969-f3c38f80-808b-11e9-94c2-41f212dfcea3.jpeg)
![banner-events](https://user-images.githubusercontent.com/44707412/58439971-f3c38f80-808b-11e9-9811-b927da23caea.jpeg)
![banner-grants](https://user-images.githubusercontent.com/44707412/58439972-f3c38f80-808b-11e9-8385-f944eecd836f.jpeg)
![banner-projects](https://user-images.githubusercontent.com/44707412/58439973-f3c38f80-808b-11e9-911e-e337934b4e64.jpeg)
![banner-topics](https://user-images.githubusercontent.com/44707412/58439975-f45c2600-808b-11e9-8f54-8cad51a765d4.jpeg)

**Comment by alex-418** [comment]
@ehbeattie need the right size for these, the current placeholder image is 1400x280px
It can be seen here: 
https://bccampus.ca/wp-content/themes/bcc-sage/dist/images/default-header.jpg

I wasn't able to find the ones you attached here in the image assets in cloud.bccampus.ca

**Comment by ehbeattie** [comment]
Try here: https://cloud.bccampus.ca/index.php/s/DkMK9pR5Fd6D9yq?path=%2FPhotos%20for%20site%20%2F*FINAL%20PHOTOS%2FPage%20Headers%20images%20(no%20transfer)%20

**Comment by alex-418** [comment]
@ehbeattie fixed the glitch with featured images showing up in the landing page results.

**Comment by ehbeattie** [comment]
Hi Alex,

It looks like the event banners got turned off along with the news sections. Is there a way to have one but not that other?

**Comment by alex-418** [comment]
@ehbeattie Yes, can do. Will update the logic so event post types can have header images.

**Comment by alex-418** [comment]
@ehbeattie done, please review and close if satisfied.

**Comment by ehbeattie** [comment]
Yaaaaas kween.
