### ISSUE TITLE
Related Events: Align bottom of content containers 

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#252]
## Submit a feature request or bug report

- [X] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

The content boxes in the "Related Events" container that appears at the bottom of  "Topics of Practice" Landing page and "Projects" Landing page do not align along the bottom of the container when the text within the box extends more than 3 lines. Attaching image for reference: 

![screen_shot_2018-10-17_at_9_17_22_pm](https://user-images.githubusercontent.com/11672469/47131264-94c6ae00-d252-11e8-9018-18c2880cc416.png)

**What is the expected or desired behavior?**

The bottom of the content containers align 

Are we able to do something like allow for a max of 3 lines of text and truncate text that extends more than that? 

adding a ... to the truncation

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/bcc-sage/commit/98eb76f168cceae893b6f3535086d04f055d7474
