### ISSUE TITLE
"Feature" event logic on hompage 

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#254]
## Submit a feature request or bug report

- [ X] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

On the homepage: https://helga.bccampus.ca/wp/bcc/

In the "Events" section, the two events, at the top in containers with an image and a purple banner behind the text are "Feature" events. These are events we want to highlight and are able to do so by manually tagging the event to appear as feature events.  

The same event, tagged to appear as a "Feature" event, appears in the "upcoming" list direclty below the "Feature" event containers. See attached for reference. 
![screen_shot_2018-10-18_at_11_24_47_am](https://user-images.githubusercontent.com/11672469/47176052-7e0f6e00-d2c9-11e8-9bba-b86e0aa29fba.png)

**What is the expected or desired behavior?**

On the home page, if an event is tagged as "Featured", it does not also appear in the "upcoming" list directly below. 

## Feature Request

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

X

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/bcc-sage/commit/ab97ebe8526136c4a7d29c6efeb728390c89a84f

**Comment by murphybarb** [comment]
Great that worked. But think it created a new issue. 

There are several upcoming events listed in the calender and they are not showing in the "Upcoming" list. Currently only "Facilitating Learning Online (FLO) – Fundamentals**" is visible in the list.   

Tried the following to get more events to display in the "Upcoming" list, none worked: 
- Created new events in the calednar for Nov 29, 2018 and Jan 17, 2019
- In new Jan 17 event duplicated the tags and categories used in the "Facilitating Learning Online (FLO) – Fundamentals**", which is displaying. But this did not work

**Comment by bdolor** [comment]
I was able to resolve it by increasing the limit from 3 to 10 (currently displaying 4 on the homepage) - We may now have less control over how many upcoming events show up...may require a re-think.

**Comment by bdolor** [comment]
as discussed in the stand up and considering current constraints, as long as the number of events that belong in the 'featured' category are less than 10, upcoming events will display. The number of upcoming events = 10 - (#of-featured-events).

**Comment by paulagaube** [comment]
@murphybarb Being devil's advocate here. Can I ask why you don't want the featured events to show up in the Upcoming Events list? Is this just on the home page? 
In the example above, the Symposium is also Featured and also shows in the Upcoming Events list. That doesn't bother me.  I kind of like to see all the upcoming events chronologically in one list. It does give "double the exposure" to that event. And if on a mobile phone, I would scroll down the list of events and see the events in date order, which I like. 

I do see that the Featured event could be taking away real estate from other, future events, but my logical brain wants to see all the events in one list by date.

**Comment by paulagaube** [comment]
Also wonder if "Featured Events" could have a badge or heading that indicates these are "featured?" (sorry, don't hit me)

**Comment by bdolor** [comment]
😈

**Comment by murphybarb** [comment]
> @murphybarb Being devil's advocate here. Can I ask why you don't want the featured events to show up in the Upcoming Events list? Is this just on the home page?
> In the example above, the Symposium is also Featured and also shows in the Upcoming Events list. That doesn't bother me. I kind of like to see all the upcoming events chronologically in one list. It does give "double the exposure" to that event. And if on a mobile phone, I would scroll down the list of events and see the events in date order, which I like.
> 
> I do see that the Featured event could be taking away real estate from other, future events, but my logical brain wants to see all the events in one list by date.

Hey @paulagaube:
Removing the featured event from the upcoming list was to avoid duplicating the event on the homepage in the events area. This only happens on the homepage. 

> Also wonder if "Featured Events" could have a badge or heading that indicates these are "featured?" (sorry, don't hit me)

Hey @paulagaube:
Great feedback, we'll consider that for the future iterations.

**Comment by paulagaube** [comment]
@murphybarb ok, thank you!!
