### ISSUE TITLE
*Topics of Practice Landing page: correct 'featured' image not displaying 

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#257]
## Submit a feature request or bug report

- [ ] This is a feature request
- [ X] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

One the topics of practice page: https://helga.bccampus.ca/wp/bcc/bccampus/topics-of-practice/

The image displaying in the "3.1 Open Education" container is the incorrect. 

**What is the expected or desired behavior?**

The "Featured" image indicated for ["3.1 Open Education" page](https://helga.bccampus.ca/wp/bcc/open-education/) should be showing, it is not. There is a featured image indicated for that page, it is not diplaying, a default image is. 

## Feature Request

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**
The 3 other containers are displaying the correct image. See attached. 

![screen shot 2018-10-18 at 12 07 46 pm](https://user-images.githubusercontent.com/11672469/47177896-91710800-d2ce-11e8-9e7d-62ff2f087240.png)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/bcc-sage/commit/6e10bb539292c314d059ca9c7a3ca291e5c7616b
