### ISSUE TITLE
Individual event pages: add "Related Events" page template

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#259]
## Submit a feature request or bug report

- [ ] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

Example page: https://helga.bccampus.ca/wp/bcc/event/symposium-2018-scholarly-teaching-learning-in-post-secondary-education-2/

Individual event pages should display "Related Events" at the bottom. 

**What is the expected or desired behavior?**

Original design mockup is attached indicating placement of "Related Events" at the bottom.

![8 events content-desktop](https://user-images.githubusercontent.com/11672469/47179178-40fba980-d2d2-11e8-9230-04c79a3e4a74.jpg)

## Feature Request

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

X

**Comment by bdolor** [comment]
can be validated at https://helga.bccampus.ca/wp/bcc/event/cascadia-open-education-summit-option-b/

**Comment by ehbeattie** [comment]
Looks good, thanks!
