### ISSUE TITLE
*CSS: H1 Font Styling 

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#261]
## Submit a feature request or bug report

- [X ] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

=
## Feature Request

**Please provide use cases for changing the current behavior:**

Update styling of H1, 

Can we add a style="font-weight: 400;" to H1

**Other relevant information:**

**Comment by bdolor** [comment]
closing based on discussion
