### ISSUE TITLE
randomize the display of opened and teaching and learning 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#265]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

Currently the posts are grabbed off the top of a list and present what appears to be stale content. 

https://helga.bccampus.ca/wp/bcc/news/

**What is the expected or desired behavior?**

The items in the category area need to be randomized in order to elevate all posts. 

---

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/bcc-sage/commit/71a466ccae2785e0d39490afa8f00139ba4ce531

**Comment by ehbeattie** [comment]
Helga only has a select amount of articles loaded for testing so I can't really validate this one until the site is live. I will have to trust you on this one.
