### ISSUE TITLE
move from tags to categories

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#266]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

**What is the current behavior?**

opened and teaching + learning are pulling from content that has been tagged. 

https://helga.bccampus.ca/wp/bcc/news/

**What is the expected or desired behavior?**

Categories are being used throughout the site and we'd like to move to that for consistency.

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/bcc-sage/commit/f5a9334555e3632130c4bf6b4f356dfed0700242

**Comment by ehbeattie** [comment]
Good stuff.
