### ISSUE TITLE
update subscription form templates to include content from wysiwyg

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#268]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

**What is the current behavior?**

templates used for forms don't allow users to add content 

https://helga.bccampus.ca/wp/bcc/news/subscribe/

**What is the expected or desired behavior?**

users should be able to add content above the form.

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/bcc-sage/commit/92c15225f6e6ce5770c3fdc5011c3c8d2ca8e0c3

**Comment by ehbeattie** [comment]
Looks good!
