### ISSUE TITLE
Customizable excerpt field 

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#275]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

The excerpt length has been established by a predetermined character count, but would like the ability to customize the copy being pulled through. 

https://helga.bccampus.ca/wp/bcc/bccampus/projects/

![screen shot 2018-11-02 at 12 08 25 pm](https://user-images.githubusercontent.com/44707412/47935582-1267fc00-de98-11e8-91fc-52cc1c9ca44c.png)

**What is the expected or desired behavior?**

We would like to have access to the excerpt field to craft and edit the copy being pulled through the pages (events, projects, etc.).

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/bcc-sage/commit/8b87460181fce62152de0cd0ab29162f1cd9ba40 

the logic is such that it will look for an excerpt value first, and if it's not empty display it. If it is empty, it will fall back to pulling content from the body of the text (as it currently does).

**Comment by bdolor** [comment]
forget to mention, excerpt box will now appear on pages

**Comment by bdolor** [comment]
grants and topics landing pages working as expected via https://github.com/BCcampus/bcc-sage/commit/4054744b0038f8243ff5a7d4e2f543d256cc0f41

**Comment by ehbeattie** [comment]
I don't show a stop to edit the excerpts...

**Comment by ehbeattie** [comment]
All good. Nicely done, Brad.
