### ISSUE TITLE
Mega Menu Top Links Have Extra Space

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/bcc-sage#276]
## Submit a feature request or bug report

- [ ] This is a feature request
- [X] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

## Bug report

**Where did the bug happen? Provide the link if possible**

The top-level links in the mega menu have a space inserted in between the link text and the down-pointing chevron.  On-hover, the space becomes underlined.  

![screen shot 2018-11-06 at 10 47 20 am](https://user-images.githubusercontent.com/43043264/48086799-9250d780-e1b2-11e8-9bcc-ebaf7344cecb.png)

**Please provide steps to reproduce**

Hover over top mega menu links.

**Please describe your local environment:**

Firefox 63 on Mac

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/wp-megawalker/commit/14325934949b52d1f02e5a363cbf341a1b5e41a6
