### ISSUE TITLE
Alignment of photo/content boxes mis-aligned

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/bcc-sage#277]
## Submit a feature request or bug report

- [ ] This is a feature request
- [X] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

The photo/text feature boxes on the "Grants and Calls..." landing page are misaligned.

<img width="968" alt="screen shot 2018-11-06 at 11 17 17 am" src="https://user-images.githubusercontent.com/43043264/48088144-09d43600-e1b6-11e8-88c8-ffddbd0ab96a.png">

**What is the expected or desired behavior?**

Align the feature boxes vertically.

---

## Bug report

**Where did the bug happen? Provide the link if possible**

https://bccampus.ca/grants-calls-for-proposals/

**Please provide steps to reproduce**

X

**Please describe your local environment:**

Web Browser name and version: Firefox 63

Operating System: Mac

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/bcc-sage/commit/d0ae163d6bf4c0eeca4545ed63c12d2c77caeb92 please ensure to clear browser cache
