### ISSUE TITLE
Missing space in mega-menu <a> tags

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/bcc-sage#278]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

There is a space missing in some of the links that are generated by the header and mega-menus.  For example from mega menu:
<a href="https://bccampus.ca/projects/fellows-program/scholarly-teaching-fellows-2018-19/"class="nav-link">
THere is a space missing between the value of the href and the class attribute: fellows-2018-19/**"c**lass="nav-link"

For example from header menu:
<a href="https://open.bccampus.ca"class="nav-link">

s.c**a"cl**ass="na

This may be the cause of some links in the mega-menu not directing clicks as expected.  For example, clicking on "Topics of Practice"->"Educational Technology" does not link to the Ed Tech page (however opening the link in a new tab works)

**What is the expected or desired behavior?**

There should be a space between each value and attribute

---

## Bug report

**Where did the bug happen? Provide the link if possible**

view-source:https://bccampus.ca/topics-of-practice/learning-teaching/facilitating-learning-online/

**Please provide steps to reproduce**

X

**Please describe your local environment:**

Web Browser name and version: FF 63

Operating System: Mac

**Comment by dshaykewich** [comment]
<img width="1014" alt="screen shot 2018-11-06 at 1 47 21 pm" src="https://user-images.githubusercontent.com/43043264/48095823-8d981d80-e1ca-11e8-9452-b34fe75a88ad.png">

**Comment by dshaykewich** [comment]
Mega menu links not working:
 - Projects -> Ed Tech Projects
 - Projects -> Ed Tech Project Archives
 - Projects -> Fellows Program
 - Grants and Calls for Proposal -> BCcampus Grants and Proposals Archive

**Comment by dshaykewich** [comment]
data-toggle="dropdown" on all those links ?

**Comment by bdolor** [comment]
is that that connection between them?

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/wp-megawalker/commit/d8377a23fc588d650fba3ba98c284816fb0f0085
