### ISSUE TITLE
Add favicon to site

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/bcc-sage#279]
## Submit a feature request or bug report

- [X] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

No favicon is displaying.

**What is the expected or desired behavior?**

Show a favicon

**Comment by ehbeattie** [comment]
Looks good! Thank you.
