### ISSUE TITLE
Mega-menu Links Not Working

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/bcc-sage#280]
## Submit a feature request or bug report

- [ ] This is a feature request
- [X] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

The following links in the mega menu do not work

    Projects -> Ed Tech Projects
    Projects -> Ed Tech Project Archives
    Projects -> Fellows Program
    Grants and Calls for Proposal -> BCcampus Grants and Proposals Archive

Those links all appear to have the attribute of:
data-toggle="dropdown" 

**What is the expected or desired behavior?**

Links work :-)

---

## Bug report

**Where did the bug happen? Provide the link if possible**

All pages in the mega menu

**Please provide steps to reproduce**

**Please describe your local environment:**

Web Browser name and version: FF 63

Operating System: Mac

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/wp-megawalker/commit/d8377a23fc588d650fba3ba98c284816fb0f0085 and https://github.com/BCcampus/bcc-sage/commit/066ddf246810f14017f236d114492bfbfcc58dcf

**Comment by ehbeattie** [comment]
Looks good!
