### ISSUE TITLE
errors from unsupported social media sharing plugin

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#282]
## Submit a feature request or bug report

- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

**What is the current behavior?**

- Social media plugin may no longer be maintained. https://wordpress.org/plugins/shariff-sharing/ 
-  It is throwing error messages on the server. 
![image](https://user-images.githubusercontent.com/2048170/48155571-1c1aa680-e280-11e8-9f0d-fbefb79825ae.png)

![image](https://user-images.githubusercontent.com/2048170/48155675-67cd5000-e280-11e8-9c67-d2eb120106f8.png)

**What is the expected or desired behavior?**

Plugins used on the site are expected to be maintained

---

## Bug report

**Where did the bug happen? Provide the link if possible**

Fatal errors occur on every page load

**Please provide steps to reproduce**

visit a page, tail the log files

**Comment by bdolor** [comment]
installed and configured new plugin on helga, please validate: 

- post: https://helga.bccampus.ca/wp/bcc/test-post-12-with-strange-characters-ampersand-quotes-space-asterics-hashtag/ 
- page: https://helga.bccampus.ca/wp/bcc/bccampus/about-2/how-we-are-funded/
- event: https://helga.bccampus.ca/wp/bcc/event/cascadia-open-education-summit-option-b/
- landing page: https://helga.bccampus.ca/wp/bcc/bccampus/about-2/

**Comment by ehbeattie** [comment]
@dshaykewich - the stats plugin was changed here, but I don't think we messed with any stats-plugins on OpenEd as it's already rich with its own stats complexities. I'm not sure where the disconnect occurred.

**Comment by dshaykewich** [comment]
Agreed @ehbeattie .  This was not the issue we're dealing with now.  We do have stats collected up until April 2019, but not afterwards.  That's why I think the disabling of the plugin had something to do with the Open site launch and/or Cascadia conference.
