### ISSUE TITLE
Formatting issues with captions in blog posts

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#283]
## Submit a feature request or bug report

- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

Blog posts with captions are not displaying as they should. Exhibit A: https://bccampus.ca/2017/05/10/virtual-reality-and-augmented-reality-field-trips-funded-by-oer-grants/

**What is the expected or desired behavior?**

The figure class or css wraps the text around an image to keep the caption below the image in a neat and tidy way. 

---

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/bcc-sage/commit/0545946bf960f44286ee0b87c2d793d107092aeb

**Comment by ehbeattie** [comment]
Sweeeeeeet.
