### ISSUE TITLE
Remove logo from footer

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#284]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

There are currently two logos on the site, both in the header and footer and they are different. 

**What is the expected or desired behavior?**

We only need one logo, please remove the one from the footer. 

---

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/bcc-sage/commit/d8b556826432314e988fb4019c5b6ca18be18753
