### ISSUE TITLE
Remove archives from event landing page

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#286]
## Submit a feature request or bug report

- [X] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

Currently, the event page lists the archives for EdTech Demos and FLO. 

https://bccampus.ca/events

**What is the expected or desired behavior?**

We would like to remove the reference to this archives from this page. Please and thank you. 

---

![screen shot 2018-11-07 at 2 10 37 pm](https://user-images.githubusercontent.com/44707412/48164376-2bf1b500-e297-11e8-9705-521efe13d558.png)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/bcc-sage/commit/4baeae0627f55f9906166a35244196fa194e36f1
