### ISSUE TITLE
Update EdTech Demo Institution list for newsletter sign ups 

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#287]
## Submit a feature request or bug report

- [ ] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

**What is the current behavior?**

The current list on the EdTech Demo sign up page doesn't represent all of the B.C. Post-Secondary institutions and their current names. This list has been updated on Campaign Monitor, but needs to be mirrored on BCcampus.ca. https://bccampus.ca/topics-of-practice/educational-technology/edtech-demos/

**What is the expected or desired behavior?**

This is the correct list: 

BCcampus
British Columbia Institute of Technology
Camosun College
Capilano University
Coast Mountain College
College of New Caledonia
College of the Rockies
Douglas College
Emily Carr University of Art + Design
Justice Institute of British Columbia
Kwantlen Polytechnic University
Langara College
Nicola Valley Institute of Technology
North Island College
Northern Lights College 
Okanagan College
Royal Roads University
Selkirk College
Simon Fraser University
Thompson Rivers University
University of British Columbia
University of British Columbia Okanagan
University of Northern British Columbia
University of the Fraser Valley
University of Victoria
Vancouver Community College
Vancouver Island University
Yukon College
Other

**Comment by bdolor** [comment]
@ehbeattie the page linked to above has a link in the page that sends users back to edtech.bccampus.ca - where is the form on the bccampus.ca site?

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/bcc-sage/commit/056694459561f52416134ecda8dabf4e0418dcca
