### ISSUE TITLE
Link event sidebar to event archive page

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#288]
## Submit a feature request or bug report

- [X] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

Currently, the event archive page has a long-winded sidebar.  See here: https://bccampus.ca/events/events-archive/

**What is the expected or desired behavior?**

Link the sidebar from this page: https://bccampus.ca/events/calendar-of-events/ to the events archive page. Pretty please. 

---

**Comment by bdolor** [comment]
will be taken care of with content
