### ISSUE TITLE
theme image 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#298]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [x] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

There is no image associated with the theme

**What is the expected or desired behavior?**

theme image provides a preview and visual context. 

---

**Please provide steps to reproduce**

go to the dashboard, theme, appearance 

![image](https://user-images.githubusercontent.com/2048170/50611032-d518ee00-0e89-11e9-9d13-410ff96e70d6.png)

---

## Feature Request

**Please provide use cases for changing the current behavior:**

I am a site administrator and I want to verify which theme is activated so that I can minimize confusion.

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/bcc-sage/commit/f8e66bbdd40eb9f0629d5bd6ede64c79ea81f55c (requires clearing your browser cache. See screenshot below for results) 

![screenshot](https://user-images.githubusercontent.com/17072191/51713478-e8c9f700-1fe6-11e9-9b40-87ea89c7e74a.png)

**Comment by ehbeattie** [comment]
Niiiiice.
