### ISSUE TITLE
Contact form captcha not strong enough

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/bcc-sage#300]
## User story/Need:
As someone who receives and replies to email submitted through the BCcampus Website contact form,
I want the spam emails that are being submitted through the form to be stop getting delivered to the support mailbox
So that I don't have to read them and manually mark them as spam. (I want them to stop, please.)

- [X] This is a feature request
- [ ] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [X] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**
Website users can submit a question to us using the Contact Us form on the BCcampus website, here:
https://bccampus.ca/about-us/contact/
The messages submitted are added to the Contact Form DB and also sent to "inquiry@bccampus.ca" which is an alias for "support@bccampus.ca"

There is a captcha installed on this Contact Us page, and Alex and I confirmed that the captcha is required to be entered before a question/comment is submitted through the form. 

The problem is that repetitive, nonsensical and offensive spam is still getting through. 

**What is the expected or desired behavior?**

No spam gets through the contact form so we don't have to see it and manually delete it. 

---
To replicate this problem:
Go go to https://bccampus.ca/about-us/contact/
Submit a nonsense message 
Enter the required captcha
Submit
Check the Contact DB to see if the submitted message got through (and check the support@bccampus.ca email account)

**Comment by alex-418** [comment]
related to https://github.com/BCcampus/eypd/issues/638

**Comment by bdolor** [comment]
I added honeypot plugin for a low hanging fruit win. We can see if it improves things and make a decision down the road to keep it or provide another solution.

**Comment by ehbeattie** [comment]
Sounds good. Thanks, all.
