### ISSUE TITLE
Footer spelling

### ISSUE THREAD

**Issue by alex-418** [BCcampus/bcc-sage#301]
A correction for the bccampus.ca footer:

- “Creative Commons…License”, License should be Licence

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/bcc-sage/commit/458b2852b4ecdd4545fad354e1b72f7a5f57436a

**Comment by kkilbey** [comment]
@alex-418 Where can I validate this? Could you send a link? Thanks!

**Comment by kkilbey** [comment]
Looks good! Moving to Done.
