### ISSUE TITLE
EdTech navigation box on the right on this page

### ISSUE THREAD

**Issue by alex-418** [BCcampus/bcc-sage#302]
Can we get the EdTech navigation box on the right on  this page? https://bccampus.ca/edtech-demo/ As well, I notice that this page does not have the navigation breadcrumb trail that would take people back to the EdTech section of the site. Could that breadcrumb be activated for this page so that it isn’t orphaned from the rest of the EdTech section? I will have to request this in the next sprint as it requires some building. 

The right navigation block does not include links to the Sandbox Project page, or the EdTech Project Archives, or to the Ally project. I would much rather see those on the main navigation block that link to past EdTech Demos for Crowdmark and WeVu. Any way we can change the navigation block so that it is consistent for all EdTech pages, and contain more important information, like our Sandbox Pilot Process, the BB Ally Project page, and

Accessibility and fine tune - BCcampus

**Comment by ehbeattie** [comment]
In looking closer at this issue, I note that it might actually require dev-ops...

The request is to include the EdTech Demos sidebar on the EdTech Demos subscription page, but being that it's a landing page as is, I'm not sure how to address this issue.
