### ISSUE TITLE
Update instances of "Helpdesk"

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/bcc-sage#306]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [x] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

The website refers users to "Helpdesk" for assistance and displays the old helpdesk email address.

**What is the expected or desired behavior?**

Instances of "Helpdesk" are updated to "Support team" as per our recent transition. We also replace the helpdesk email address with either a link to the Contact form or with the inquiry@bccampus.ca email address.

**Comment by paulagaube** [comment]
I'm pretty sure this has been done. Will check tomorrow and then close this issue.

**Comment by alex-418** [comment]
@paulagaube okay to close this? tnx

**Comment by paulagaube** [comment]
Yes, closing this issue! Thank you!
