### ISSUE TITLE
Add FAQ page

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/bcc-sage#307]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [x] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

Currently, the Help page redirects users to CustomAnswers, where they can browse FAQs and contact us through the "Submit a Request" form.

**What is the expected or desired behavior?**

As we are moving away from CustomAnswers, we need to create a Help page on the BCcampus site and transfer our FAQs there. This may involve using an existing template to create a new page or installing a plugin (as done on the EYPD site). Investigating to figure out the best option...

**Comment by paulagaube** [comment]
This is done. Closing this issue.
