### ISSUE TITLE
Function to remove/filter past related events

### ISSUE THREAD

**Issue by alex-418** [BCcampus/bcc-sage#309]
Related events should only show future events, not past events.

**Comment by bdolor** [comment]
ready for validation...note: 

> short of removing events, it prefers more recent events with a specified sort order (based on date). The goal of the `getRelated()` function is to return a fixed number of posts related to the existing post and if there are no related events in the future, a graceful degradation is to present related events in the past. Fixing the sort order gives preference to most recent events while still being able to deliver on requirement of a fixed number of related events.

**Comment by ehbeattie** [comment]
Ok. I've moved it to the done column.
