### ISSUE TITLE
WordPress Image Compression and Optimization

### ISSUE THREAD

**Issue by alex-418** [BCcampus/bcc-sage#318]
**Is your feature request related to a problem? Please describe.**
Images that are uploaded to events, pages, or posts are too large and cause website performance issues (see #219). 

**Describe the solution you'd like**
All existing and future uploaded images on the website need lossless compression applied to strip unused data to reduce file size, without affecting image quality. This could be achieved by a plugin. We need to either create or find one that solves this problem in the most elegant way. 

**Describe alternatives you've considered** 
1. We could do this at the web server level, via Google's [Apache PageSpeed](https://www.modpagespeed.com/doc/filter-image-optimize). 
2. We could introduce a CDN(<a href="https://www.akamai.com/us/en/solutions/why-akamai/image-management.jsp">Akamai</a>) or 3rd-party(<a href="https://imageoptim.com/api">ImageOptim API</a>) to handle this for us.
3. We could require users to optimize/compress the image to before uploading them to the website.

**Comment by alex-418** [comment]
@ehbeattie to review, @dshaykewich happy to provide support with image optimization decisions

**Comment by ehbeattie** [comment]
Update: I've submitted a request to have graphics created for our blog posts that are web optimized. 

> Hi Jessica, 
> 
> Can you create a suite of generic, BCcampus-themed graphics that we can use as feature images for all posts that are web optimized and beautiful?
> 
> We would like 3 for each:
> 
> BCcampus
> OpenEd
> Learning + Teaching
> Collaborative Projects
> Educational Technology
> 
> I really love the look, feel and diversity of the header image on this site, but perhaps with a few with lighter backgrounds as well? They don't necessarily need words is it doesn't always work in all spaces (examples in Basecamp).
> 
> http://bccampusannualreview.ca/
> 

Cheers,

Erin
