### ISSUE TITLE
Kill "Display Preferences" tabby

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#345]
**Is your feature request related to a problem? Please describe.**
The current header is much too tall. It’s taking up valuable screen real estate and needs general design improvements.

**Describe the solution you'd like**
Change the styling of the "Display Preferences"  - It needs to be styled to match the website. 

**Describe alternatives you've considered**

- It should be a more subtle text link with an icon.
- Using the same dark grey as the Help and Contact links.
- It should align to the 12 column grid just like the two menu rows below.
- Not so much space below it, we can tighten up this space a lot.

**Comment by alex-418** [comment]
Also remove on BCcampus/open-sage

**Comment by alex-418** [comment]
@ehbeattie this is now gone from bccampus.ca and open.bccampus.ca 

via https://github.com/BCcampus/bcc-sage/commit/4c5ce4c899ca5adc5bbcb44789b97c89dc119309 and https://github.com/BCcampus/open-sage/commit/88a7d96d6a265af1c08c3fece2cd379a00eb93f7

**Comment by ehbeattie** [comment]
@alex-418 Yaaaaassssssss!
