### ISSUE TITLE
Update the secondary menu styling 

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#346]
**Is your feature request related to a problem? Please describe.**
There is too much spacing around the menu, creating too much of a scroll for users. 

**Describe the solution you'd like**
Please match the styling outlined in the original mock-ups. 

**Describe alternatives you've considered**
-	These elements should all align to the right
-	The search box needs to be styled to match the site as per mockup 
-	The correct blue to use for the links is #009dd6

<img width="972" alt="Screen Shot 2019-05-27 at 2 39 12 PM" src="https://user-images.githubusercontent.com/44707412/58440197-4b162f80-808d-11e9-96db-65a984199e46.png">

**Comment by alex-418** [comment]
Replaced by #353
