### ISSUE TITLE
Update the primary menu styling

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#347]
**Is your feature request related to a problem? Please describe.**
The primary menu doesn't quite look/function as well as it could. 

**Describe the solution you'd like**
Please follow the mock-ups as closely as possible. 

**Describe alternatives you've considered**

-	This needs to be much higher up, there’s currently a lot of space between where the logo ends and the navigation begins
-	The links should be black, and were not supposed to have arrows.

<img width="972" alt="Screen Shot 2019-05-27 at 2 39 12 PM" src="https://user-images.githubusercontent.com/44707412/58440281-d0014900-808d-11e9-8fcd-3671c3429669.png">

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/bcc-sage/commit/88c9e7ea25e5146dbe6e0e211b8f4c90b7ddf518 

Nav link color is now black as per design, and vertical space of primary nav is reduced. Please clear browsers cache to see the following changes:

![nav](https://user-images.githubusercontent.com/17072191/58729402-2cba7780-839e-11e9-8538-0a2824ffb0a9.png)

**Comment by alex-418** [comment]
@ehbeattie Mobile link color now updated as well.

**Comment by ehbeattie** [comment]
Marvellous!
