### ISSUE TITLE
Update the mega menu styling 

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#348]
**Is your feature request related to a problem? Please describe.**
The mega menu isn't functioning as well as it could/should. 

**Describe the solution you'd like**
Please try to match the mock-ups as much as possible. 

**Describe alternatives you've considered**
-	The grey background was supposed to be full-width
-	The photo on the left is intended to match the header/banner photo of that sections pages (the one shown here is a placeholder)
-	There is supposed to be a title in the top left, overlayed on top of the photo
-	The navigation links were intended to be black to contrast the background and match the menu links above, with a blue hover state using #009dd6.
-	The grid was supposed to be  4/12 + 8/12 so that way it would match the page layouts, and then the 8/12 section was supposed to be sub-gridded with the options for a 2, 3 or 4 column layout (i know this is possible with the framework, you just need to wrap it in a row class first within the 8/12 column).
<img width="867" alt="Screen Shot 2019-05-27 at 2 47 05 PM" src="https://user-images.githubusercontent.com/44707412/58440357-59188000-808e-11e9-980b-119526332196.png">

**Comment by alex-418** [comment]
Replaced by #353
