### ISSUE TITLE
General updates to the homepage

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#350]
**Is your feature request related to a problem? Please describe.**
The homepage doesn't look as crisp and polished as it could/should. 

**Describe the solution you'd like**
Please match the mock-ups as best that you can. 

**Describe alternatives you've considered**
-	These images look really pixelated on the live site, can you please load a higher quality image.
-	use my arrows and vertically center them
-	No rounded corners
-	Adjust the padding around the text on the live site to look more like this
-	Now that the site is being used, I see a lot of the images being uploaded are very light or on white backgrounds. Everything looked fine in the mockups because we used real photos. I’d like to suggest that we do a very subtle overlay on the featured photos to get them just a shade darker.
- Are you able to do a subtle overlay using our dark purple:
- background: rgba(54,43,99,.15)
- (Since I see that some are transparent png’s, we would need to overlay the colour on top of them rather than applying a background colour and adjusting the images opacity.)
- Originally I had mocked up the logo here to fill the space, but I think we should put the Territorial Acknowledgement here and remove it from the black copyright bar. So that way we can tighten up the spacing in that black bar and make it less tall.
-	Correct blue for bullets and button background #009dd6
-	Please make both titles the same size
-	Make sure all text in this area is black #000

<img width="600" alt="Screen Shot 2019-05-27 at 2 54 51 PM" src="https://user-images.githubusercontent.com/44707412/58440547-92052480-808f-11e9-8b00-cdcc41c23779.png">

**Comment by ehbeattie** [comment]
@stargraphicdesign - Reminder to please update the acknowledgement while you move it.

**Comment by stargraphicdesign** [comment]
Hey Alex
I actually can't find anywhere in wordpress to put custom css overrides, it looks like my user doesn't have access to those places.

**Comment by alex-418** [comment]
@stargraphicdesign Can you see the appearance menu? Select "Customize" and there should be a "custom css" option there. Let me know if that worked for you.

**Comment by stargraphicdesign** [comment]
@alex-418  My customize panel doesnt have a CSS section
![Screen Shot 2019-06-05 at 2 15 51 PM](https://user-images.githubusercontent.com/1656362/58991169-73dcaa00-879c-11e9-9e39-559d589b55e6.png)

**Comment by alex-418** [comment]
@stargraphicdesign Thanks for screenshot, we're on WP multisite so this has to be enabled for site admins. I've done that now, let me know if it's showing up now?

**Comment by stargraphicdesign** [comment]
i'm closing this because i've made all the adjustments i can, and will be tasking Alex with the rest

**Comment by alex-418** [comment]
@ehbeattie I noticed this one was re-opened, is there anything missing that you'd like me to tackle?
