### ISSUE TITLE
Search: Sort by most recent first

### ISSUE THREAD

**Issue by alex-418** [BCcampus/bcc-sage#352]
Improve the built in WordPress search to be sorted by most recent first, rather than the keyword match that is happening now.

**Comment by alex-418** [comment]
@ehbeattie There was some really funky stuff going on with the search. Two plugins were modifying the query, so applying the custom sort order did not work on production. Removed one of them (search regex) because I did not see it's purpose, and it hasn't been updated it a long time. The other one is "Relevanssi" which takes over the query, so i've updated that to sort by date (descending). Here's the results: https://bccampus.ca/?s=textbooks 

Only posts have post dates, the first few you can see the dates. Let me know if that works as expected.

**Comment by ehbeattie** [comment]
This is terrific!!
