### ISSUE TITLE
Switch Mega-Menu to Regular menu

### ISSUE THREAD

**Issue by alex-418** [BCcampus/bcc-sage#353]
@ehbeattie @dshaykewich Decided to replace the mega menu, and move all of the sub-items into the pages sidebar menu.

**Comment by alex-418** [comment]
Split Events menu item into two pages: Events Page and Events Calendar page

**Comment by ehbeattie** [comment]
Question: If we change the menu structure/navigation... do we risk breaking links and bookmarks?

**Comment by alex-418** [comment]
@ehbeattie Answer: No impact. Links will remain the same, so bookmarks would not be impacted.

**Comment by ehbeattie** [comment]
I like this answer. Please proceed.

**Comment by alex-418** [comment]
@ehbeattie take the new menu for a spin! https://bccampus.ca

**Comment by ehbeattie** [comment]
@alex-418 I LOVE IT!! 

There are some changes required to the Call for Proposals, but I think I should wait until issue #360 is addressed before I jump in there. I've pushed that one up in the "to do" list. I hope that's ok.

**Comment by ehbeattie** [comment]
@alex-418 Yaaaaaaaas kween!
