### ISSUE TITLE
Create Events Landing Page

### ISSUE THREAD

**Issue by alex-418** [BCcampus/bcc-sage#354]
Include a sidebar menu for orphaned mega menu items.

**Comment by ehbeattie** [comment]
We have the draft content here: https://bccampus.ca/events_

There is a spot for a listing of upcoming BCcampus-hosted events that need to be manually added/removed so maybe we could come up with a system to auto-populate these?

Cheers,

Erin

**Comment by alex-418** [comment]
@ehbeattie Checkout the new events page https://bccampus.ca/events/ and https://bccampus.ca/calendar/ ... let me know if these look good to you. Will confirm all of the menu items made it in when tackling #353

**Comment by ehbeattie** [comment]
Hi,

I like it. Is there anyway to manipulate which events show up here? Or add more...?

Cheers,

Erin

**Comment by ehbeattie** [comment]
<img width="591" alt="Screen Shot 2019-05-29 at 4 17 04 PM" src="https://user-images.githubusercontent.com/44707412/58597524-3a9cbb00-822d-11e9-9286-48f0f3e9489c.png">

**Comment by alex-418** [comment]
The Events page shows the latest 4 events that have the category "BCCAMPUS EVENT"

**Comment by ehbeattie** [comment]
I see. I think I can work with that and mess with it. Mwhaha

**Comment by alex-418** [comment]
The calendar page is the "EdTech" category and the "Facilitating Learning Online" category. I can also show a list like you posted instead, also this page exists that is the event list/archive: https://bccampus.ca/event/

**Comment by ehbeattie** [comment]
I prefer this layout. https://bccampus.ca/events/

Is there anyway to make the sizing static for the upcoming event boxes so they don't run a muck?

**Comment by alex-418** [comment]
Todo: Fix image width issue

**Comment by alex-418** [comment]
@ehbeattie Please clear browsers cache and visit https://bccampus.ca/events/ to confirm weird size is gone. Finally tracked it down to this styling that was overriding the bootstrap padding on only the first and last items: 

![why](https://user-images.githubusercontent.com/17072191/58666250-a6435e80-82e7-11e9-9fda-cef8facbab91.png)

**Comment by ehbeattie** [comment]
@alex-418 It still looks funky to me, but it's likely a user error. I'm calling this a win!
