### ISSUE TITLE
Staff List on BCcampus.ca needs attention

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/bcc-sage#355]
**Is your feature request related to a problem? Please describe.**
The list of BCcampus staff does not display alphabetically on a mobile phone, with Mary and Denise listed at the top. 

This is the page: https://bccampus.ca/about-us/who-we-are/

We recently manually alphabetized the list of names, alternating them over two columns, (left to right, left to right) but when viewed on a mobile phone, the first column is displayed first at the top of the page, followed by the names in the second column, which means the names are displayed out of order.

**Describe the solution you'd like**
List Mary and Denise at the top, and follow with an alphabetical list of remaining employees.

**Describe alternatives you've considered**
Listing the names alphabetically first on the left hand column, then on the right hand column
or
Breaking the names into groups of two, (only one left column, and one right column per pair), so they collapse nicely. (This sounds manual and painful.)
or
Use a plugin that allow drag and drop for each name as a unit so we can manually order them? 

**Additional context**
Add any other context, user story or screenshots about the feature request here.
As a BCcampus website user, 
I would like to view an alphabetical staff list on my mobile phone
So that I can find the person I want to contact easily on the list.

As a BCcampus.ca web administrator,
I would like to be able to easily modify the staff list
So that the staff list displays alphabetically on the website.

**Comment by alex-418** [comment]
Need to discuss to find the best solution

**Comment by alex-418** [comment]
@paulagaube Completed. Please see https://bccampus.ca/about-us/who-we-are/
