### ISSUE TITLE
Change the functionality of the Grants/Calls page

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#360]
Change the Grants/Call for Proposals functionality to pull pages/posts rather than events so that they don't appear in the event sections.

Have pages/posts live on the Grants/ Calls for Proposals page, and move from open to closed depending on a start/end date.

**Comment by ehbeattie** [comment]
@alex-418 - the "Currently Closed Opportunities" section seems redundant as there is already an archive section in the side nav. Perhaps you could remove that and rename the "Open Call for Proposals" to "Call for Proposals"?

**Comment by ehbeattie** [comment]
So. Many. Layers.

**Comment by alex-418** [comment]
@ehbeattie Sounds good to me... will do.

**Comment by alex-418** [comment]
Please see https://bccampus.ca/grants-calls-for-proposals/

The proposals are now pages (i've left the old event page for 2019 Symposium as discussed), and appear on the landing page as long as it has the following custom field (case sensitive):

![status_field](https://user-images.githubusercontent.com/17072191/58673019-69cf2d00-82fe-11e9-93c8-3d1cae8fda3b.png)

I'm also using this custom field to display the status on the proposal page itself, in case someone lands on it from google or the sidebar menu:

![status](https://user-images.githubusercontent.com/17072191/58673054-84a1a180-82fe-11e9-8bf9-8881941f922f.png)

Please let me know if that works for you, and if any other changes are needed here.

**Comment by ehbeattie** [comment]
@alex-418 I love all of this! I noticed that the archive page got pulled into the "open" section... is that on purpose?

As for the Symposium page and duplicate event for the Call for Proposals, it's a good workaround and will only be an issue until it closes on June 14.

**Comment by alex-418** [comment]
@ehbeattie That section is just a list of child pages, just like the right side menu.
