### ISSUE TITLE
Changing tabs on the individual event pages

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#361]
The current layout of the event pages is confusing for some users and requires scrolling before all the event information is displayed. Also, the information is clustered together in tabs that wrap around and doesn't display well. 

**Describe the solution you'd like**
 I am open solutions.

**Describe alternatives you've considered**
I've considered an accordion/hamburger on the side to look like right side navigation to display all the information currently in the tabby tabs.

**Comment by alex-418** [comment]
@ehbeattie Very confusing indeed ... for me, when trying to navigate to an event that had these tabs, I found the flow to getting to there a bit strange. Here's the page the calendar sent me to: https://bccampus.ca/event/748171/?instance_id=2810 and then for the tabs to display and get the event information, I had to click on the "More Information" link at the bottom of that page, which took me to https://bccampus.ca/event/2019-symposium/

**Comment by alex-418** [comment]
During our standup meeting we decided to remove the tabbing functionality on event pages, and switch to using headings with anchor links. This requires removing the shortcodes from events that use tabs, once that's completed the "Tabby Responsive Tabs" plugin can be disabled.

**Comment by ehbeattie** [comment]
It looks way better to just remove the tabby tabs. 

https://bccampus.ca/event/2019-symposium/

**Comment by ehbeattie** [comment]
And here: https://bccampus.ca/event/2019-symposium-pre-conference-liberating-structures/?instance_id=2804
