### ISSUE TITLE
Update dependencies and test changes 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/bcc-sage#368]
Depandabot has identified the following updates to our dependencies: https://github.com/BCcampus/bcc-sage/pulls

 The Bootstrap and jQuery ones are security related and require thorough testing.

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/bcc-sage/commit/2eeb2e3fe3eaa4f451eec800211118e0df927fc2 

Everything went well, I don't see any conflicts or issues with the new dependencies.

**Comment by dshaykewich** [comment]
Excellent news, @alex-418 !
