### ISSUE TITLE
Territorial Acknowledgement

### ISSUE THREAD

**Issue by stargraphicdesign** [BCcampus/bcc-sage#370]
Could you please remove the territorial acknowledgement from the black footer bar

I have added it via the Widgets in wordpress to just under the social media icons. it's not appearing for some reason, so if you could take a look and let me know if it's caching? Or if there's something blocking widget changes?

Reference image attached:
<img width="445" alt="Screen Shot 2019-06-05 at 11 32 43 AM" src="https://user-images.githubusercontent.com/1656362/58980696-cc547d00-8785-11e9-8493-cb3d98487602.png">

Updated text from Erin: "For thousands of years the Coast Salish, Lkwungen, and W̱SÁNEĆ Peoples have walked gently on the unceded territories where we now live, work, and play. We are committed to building relationships with the first peoples here, one based in honour and respect, and we thank them for their hospitality."

**Comment by alex-418** [comment]
@stargraphicdesign That area is not "widgetized" so that's why it wasn't applying the changes you made. I've removed the territorial acknowledgment from the footer, and added the new one below the social media icons as per your instructions and give it the following class:`p.acknowledgment`

**Comment by stargraphicdesign** [comment]
Thank you

**Comment by ehbeattie** [comment]
Hi,

Can we change it again to: 

For thousands of years the səl̓ilwətaɁɬ təməxʷ (Tsleil-Waututh), Skwxwú7mesh-ulh Temíx̱w (Squamish), W̱SÁNEĆ, and the Songhees Nation of the Lək̓ʷəŋən (Lekwungen) Peoples have walked gently on the unceded territories where we now live, work, and play. We are committed to building relationships with the first peoples here, one based in honour and respect, and we thank them for their hospitality.

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/bcc-sage/commit/15bf3fffff1bf260a6d710c441dd3052649f65f7
