### ISSUE TITLE
Re-Arrange Footer Content

### ISSUE THREAD

**Issue by stargraphicdesign** [BCcampus/bcc-sage#371]
Now that the territorial acknowledgement is in the footer, it's not quite working for us design-wise so I'd like things shuffled around please.

BEFORE:
![footer-before](https://user-images.githubusercontent.com/1656362/59135153-c8b22900-8932-11e9-8b87-e7f455299550.png)

AFTER:
![footer-after](https://user-images.githubusercontent.com/1656362/59135157-ccde4680-8932-11e9-852d-31c0b1ae9bc8.jpg)

Steps:
- Add a title to column 1 "Connect With Us"
- Move the newsletter sentence and button to Column 1
- Move acknowledgement to 3rd column and change title
- I also need the newsletter text updated to "Get the latest information on news and events by subscribing to the BCcampus newsletter."

**Comment by alex-418** [comment]
Thanks @stargraphicdesign I've made these changes, let me know if anything else is needed here.

**Comment by ehbeattie** [comment]
Hi! The site is looking awesome! Alex, can you remove some of the bottom padding from the privacy/copyright footer? 

Cheers,
Erin

**Comment by alex-418** [comment]
@ehbeattie Sure no problem, I've updated this. Let me know if you're happy with the change.

**Comment by ehbeattie** [comment]
It's perfect. Thank you!
