### ISSUE TITLE
Change the wording from Call to Calls on Grants/CfP page

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#372]
Hi Alex,

Can you please change this from singular to plural? 

From: Call from Proposals to Calls to Proposals

![Screen Shot 2019-06-27 at 3 39 44 PM](https://user-images.githubusercontent.com/44707412/60305662-34fcc880-98f2-11e9-8dc9-45b999861872.png)

**Comment by ehbeattie** [comment]
https://bccampus.ca/grants-calls-for-proposals/

**Comment by alex-418** [comment]
@ehbeattie done.
