### ISSUE TITLE
Email authentication 

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#382]
Hi,

We are noticing that many emails are going to the junk folder since the migration to Office 365. To rectify this, perhaps enabling DMARC to our DNS records and ensuring DKIM and SPF might help?

It would appear that Outlook is aggravating the issue as the servers appear to be different than the ones we were using before and the MX records don't show any of the outlook config info, so it might be causing some issues. I am 100% guessing this is the issue and I welcome any other solutions. 

https://mxtoolbox.com/domain/bccampus.ca/
https://www.campaignmonitor.com/blog/email-marketing/2016/05/email-authentication-solving-mystery-authentication/

Cheers,

Erin

**Comment by dshaykewich** [comment]
@ehbeattie - for clarification... Are you saying that email that we're trying to deliver to our stakeholders is ending up in their junk folders, or are emails others are sending us ending up in our junk mail folders?

**Comment by ehbeattie** [comment]
@dshaykewich both. If it's coming through a 3rd party, such as Campaign Monitor, it seems to end up in the junk folder.

**Comment by dshaykewich** [comment]
@ehbeattie -- this kind of config/troubleshooting is in the realm of George/Brian (as they're the ones who can get into the config side of things).  I'd suggest opening a ticket with IT Support on this one.

**Comment by ehbeattie** [comment]
@paulagaube - are you able to assist with the above?

**Comment by paulagaube** [comment]
@ehbeattie I opened a ticket in JIRA for this so George will see it when he gets back from vacation. 
https://jira.bccampus.ca/browse/AS-90

**Comment by ehbeattie** [comment]
Fab, thanks, @paulagaube
